/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { LookupCurpRequestGender } from "../../types/LookupCurpRequestGender";

export const LookupCurpRequest: core.serialization.Schema<
    serializers.LookupCurpRequest.Raw,
    OrigoidApi.LookupCurpRequest
> = core.serialization.object({
    givenNames: core.serialization.string(),
    firstSurname: core.serialization.string(),
    secondSurname: core.serialization.string().optional(),
    dateOfBirth: core.serialization.string(),
    gender: LookupCurpRequestGender,
    birthStateCode: core.serialization.string(),
    generateRfc: core.serialization.boolean().optional(),
});

export declare namespace LookupCurpRequest {
    export interface Raw {
        givenNames: string;
        firstSurname: string;
        secondSurname?: string | null;
        dateOfBirth: string;
        gender: LookupCurpRequestGender.Raw;
        birthStateCode: string;
        generateRfc?: boolean | null;
    }
}
