/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const ValidateCurpRequest: core.serialization.Schema<
    serializers.ValidateCurpRequest.Raw,
    OrigoidApi.ValidateCurpRequest
> = core.serialization.object({
    curp: core.serialization.string(),
    generateRfc: core.serialization.boolean().optional(),
});

export declare namespace ValidateCurpRequest {
    export interface Raw {
        curp: string;
        generateRfc?: boolean | null;
    }
}
