/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OrigoidApi from "../../../../api/index";
import * as core from "../../../../core";

export const SearchPepsRequest: core.serialization.Schema<
    serializers.SearchPepsRequest.Raw,
    OrigoidApi.SearchPepsRequest
> = core.serialization.undiscriminatedUnion([core.serialization.unknown()]);

export declare namespace SearchPepsRequest {
    export type Raw = unknown;
}
