/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OrigoidApi from "../../../../api/index";
import * as core from "../../../../core";

export const SearchSat69BRequest: core.serialization.Schema<
    serializers.SearchSat69BRequest.Raw,
    OrigoidApi.SearchSat69BRequest
> = core.serialization.undiscriminatedUnion([core.serialization.unknown()]);

export declare namespace SearchSat69BRequest {
    export type Raw = unknown;
}
