/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OrigoidApi from "../../../../api/index";
import * as core from "../../../../core";

export const SearchSat69Request: core.serialization.Schema<
    serializers.SearchSat69Request.Raw,
    OrigoidApi.SearchSat69Request
> = core.serialization.undiscriminatedUnion([core.serialization.unknown()]);

export declare namespace SearchSat69Request {
    export type Raw = unknown;
}
