/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const ExtractProofOfAddressRequest: core.serialization.Schema<
    serializers.ExtractProofOfAddressRequest.Raw,
    OrigoidApi.ExtractProofOfAddressRequest
> = core.serialization.object({
    file: core.serialization.string(),
});

export declare namespace ExtractProofOfAddressRequest {
    export interface Raw {
        file: string;
    }
}
