export * as renapo from "./renapo";
export * from "./renapo/types";
export * as socialSecurity from "./socialSecurity";
export * from "./socialSecurity/types";
export * as ine from "./ine";
export * from "./ine/types";
export * as biometrics from "./biometrics";
export * from "./biometrics/types";
export * as compliance from "./compliance";
export * from "./compliance/types";
export * as fiscal from "./fiscal";
export * from "./fiscal/types";
export * as banking from "./banking";
export * from "./banking/types";
export * as authentication from "./authentication";
export * from "./authentication/client/requests";
export * from "./renapo/client/requests";
export * from "./socialSecurity/client/requests";
export * from "./ine/client/requests";
export * from "./biometrics/client/requests";
export * from "./compliance/client/requests";
export * as email from "./email";
export * from "./email/client/requests";
export * as proofOfAddress from "./proofOfAddress";
export * from "./proofOfAddress/client/requests";
export * from "./fiscal/client/requests";
