/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const ValidateEmailRequest: core.serialization.Schema<
    serializers.ValidateEmailRequest.Raw,
    OrigoidApi.ValidateEmailRequest
> = core.serialization.object({
    email: core.serialization.string(),
});

export declare namespace ValidateEmailRequest {
    export interface Raw {
        email: string;
    }
}
