/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "JOAQUIN GUZMAN LOERA"
 *     }
 *
 * @example
 *     {
 *         name: "JOAQUIN GUZMAN LOERA"
 *     }
 *
 * @example
 *     {
 *         name: "JOAQUIN GUZMAN LOERA"
 *     }
 *
 * @example
 *     {
 *         name: "JOAQUIN GUZMAN LOERA"
 *     }
 *
 * @example
 *     {
 *         name: "JOAQUIN GUZMAN LOERA"
 *     }
 */
export interface SearchOfacRequest {
    /** Full name of the individual or Legal Name of the entity. */
    name: string;
    /** Minimum similarity score (50-100) required to return a fuzzy match. Defaults to 85. */
    minSimilarityScore?: number;
}
