/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class OrigoidApiTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, OrigoidApiTimeoutError.prototype);
    }
}
