/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         file: "file"
 *     }
 *
 * @example
 *     {
 *         file: "file"
 *     }
 *
 * @example
 *     {
 *         file: "file"
 *     }
 *
 * @example
 *     {
 *         file: "file"
 *     }
 *
 * @example
 *     {
 *         file: "file"
 *     }
 *
 * @example
 *     {
 *         file: "file"
 *     }
 *
 * @example
 *     {
 *         file: "file"
 *     }
 *
 * @example
 *     {
 *         file: "file"
 *     }
 *
 * @example
 *     {
 *         file: "file"
 *     }
 *
 * @example
 *     {
 *         file: "file"
 *     }
 */
export interface ExtractProofOfAddressRequest {
    /** Proof of Address file in Base64 (PNG, JPG, or PDF). */
    file: string;
}
