/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09",
 *         generateRfc: true
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 */
export interface ExtractCurpDocumentRequest {
    /** The 18-character CURP whose official document is requested. */
    curp: string;
    /** Generate the RFC associated with the CURP. Deterministic from the CURP (no SAT call). When true, `personalInfo.rfc` is included — same as `curp-validations`. */
    generateRfc?: boolean;
}
