/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../../../../index";

/**
 * @example
 *     {
 *         givenNames: "JUAN",
 *         firstSurname: "PEREZ",
 *         dateOfBirth: "1990-01-01",
 *         gender: "H",
 *         birthStateCode: "DF"
 *     }
 *
 * @example
 *     {
 *         givenNames: "JUAN",
 *         firstSurname: "PEREZ",
 *         dateOfBirth: "1990-01-01",
 *         gender: "H",
 *         birthStateCode: "DF"
 *     }
 *
 * @example
 *     {
 *         givenNames: "JUAN",
 *         firstSurname: "PEREZ",
 *         dateOfBirth: "1990-01-01",
 *         gender: "H",
 *         birthStateCode: "DF"
 *     }
 *
 * @example
 *     {
 *         givenNames: "JUAN",
 *         firstSurname: "PEREZ",
 *         dateOfBirth: "1990-01-01",
 *         gender: "H",
 *         birthStateCode: "DF"
 *     }
 *
 * @example
 *     {
 *         givenNames: "JUAN",
 *         firstSurname: "PEREZ",
 *         dateOfBirth: "1990-01-01",
 *         gender: "H",
 *         birthStateCode: "DF"
 *     }
 *
 * @example
 *     {
 *         givenNames: "JUAN",
 *         firstSurname: "PEREZ",
 *         dateOfBirth: "1990-01-01",
 *         gender: "H",
 *         birthStateCode: "DF"
 *     }
 *
 * @example
 *     {
 *         givenNames: "JUAN",
 *         firstSurname: "PEREZ",
 *         dateOfBirth: "1990-01-01",
 *         gender: "H",
 *         birthStateCode: "DF"
 *     }
 *
 * @example
 *     {
 *         givenNames: "JUAN",
 *         firstSurname: "PEREZ",
 *         dateOfBirth: "1990-01-01",
 *         gender: "H",
 *         birthStateCode: "DF"
 *     }
 *
 * @example
 *     {
 *         givenNames: "JUAN",
 *         firstSurname: "PEREZ",
 *         dateOfBirth: "1990-01-01",
 *         gender: "H",
 *         birthStateCode: "DF"
 *     }
 *
 * @example
 *     {
 *         givenNames: "JUAN",
 *         firstSurname: "PEREZ",
 *         dateOfBirth: "1990-01-01",
 *         gender: "H",
 *         birthStateCode: "DF"
 *     }
 */
export interface LookupCurpRequest {
    givenNames: string;
    firstSurname: string;
    secondSurname?: string;
    /** Format YYYY-MM-DD */
    dateOfBirth: string;
    gender: OrigoidApi.LookupCurpRequestGender;
    birthStateCode: string;
    generateRfc?: boolean;
}
