/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 *
 * @example
 *     {
 *         curp: "TEST900101HDFRRN09"
 *     }
 */
export interface ValidateCurpRequest {
    /** CURP to validate (18 characters). */
    curp: string;
    /** Generate RFC associated with the CURP. */
    generateRfc?: boolean;
}
