/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as OrigoidApi from "../../../index";
import * as serializers from "../../../../serialization/index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace SocialSecurity {
    export interface Options {
        environment?: core.Supplier<environments.OrigoidApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

/**
 * Employment and social security data.
 */
export class SocialSecurity {
    constructor(protected readonly _options: SocialSecurity.Options) {}

    /**
     * **Credits:** 1 per call.
     *
     * Retrieves a worker's NSS (Número de Seguridad Social) from IMSS based on CURP. Returns the 11-digit NSS.
     *
     * Use this endpoint when onboarding employees for payroll or social-security registration: a CURP is far easier to collect than asking the candidate for their NSS card, which is frequently misplaced.
     *
     * @param {OrigoidApi.LookupImssNssRequest} request
     * @param {SocialSecurity.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrigoidApi.UnauthorizedError}
     * @throws {@link OrigoidApi.TooManyRequestsError}
     *
     * @example
     *     await client.socialSecurity.lookupImssNss({
     *         curp: "ALMR900805HDFRZA09"
     *     })
     */
    public lookupImssNss(
        request: OrigoidApi.LookupImssNssRequest,
        requestOptions?: SocialSecurity.RequestOptions,
    ): core.HttpResponsePromise<OrigoidApi.Envelope> {
        return core.HttpResponsePromise.fromPromise(this.__lookupImssNss(request, requestOptions));
    }

    private async __lookupImssNss(
        request: OrigoidApi.LookupImssNssRequest,
        requestOptions?: SocialSecurity.RequestOptions,
    ): Promise<core.WithRawResponse<OrigoidApi.Envelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrigoidApiEnvironment.Default,
                "mex/social-security/v1/imss-nss-lookups",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@origoid/sdk",
                "X-Fern-SDK-Version": "0.5.0",
                "User-Agent": "@origoid/sdk/0.5.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.LookupImssNssRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.Envelope.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrigoidApi.UnauthorizedError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new OrigoidApi.TooManyRequestsError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OrigoidApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrigoidApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrigoidApiTimeoutError(
                    "Timeout exceeded when calling POST /mex/social-security/v1/imss-nss-lookups.",
                );
            case "unknown":
                throw new errors.OrigoidApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * **Credits:** 1 per call.
     *
     * Returns the current IMSS employment status of a worker (identified by CURP + NSS): whether they are currently registered as employed, inactive (no current registration), the modality of registration, the registered employer's RFC, employer name, state, base salary, contributed days, and the period the IMSS report covers.
     *
     * Use this endpoint for income verification (lending, leasing), employment confirmation (background checks), or to detect overlapping employment when complying with employment regulations.
     *
     * @param {OrigoidApi.GetImssEmploymentStatusRequest} request
     * @param {SocialSecurity.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrigoidApi.UnauthorizedError}
     * @throws {@link OrigoidApi.TooManyRequestsError}
     *
     * @example
     *     await client.socialSecurity.getImssEmploymentStatus({
     *         curp: "GARM900101HDFRZA01",
     *         nss: "92038109713"
     *     })
     */
    public getImssEmploymentStatus(
        request: OrigoidApi.GetImssEmploymentStatusRequest,
        requestOptions?: SocialSecurity.RequestOptions,
    ): core.HttpResponsePromise<OrigoidApi.Envelope> {
        return core.HttpResponsePromise.fromPromise(this.__getImssEmploymentStatus(request, requestOptions));
    }

    private async __getImssEmploymentStatus(
        request: OrigoidApi.GetImssEmploymentStatusRequest,
        requestOptions?: SocialSecurity.RequestOptions,
    ): Promise<core.WithRawResponse<OrigoidApi.Envelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrigoidApiEnvironment.Default,
                "mex/social-security/v1/imss-employment-status",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@origoid/sdk",
                "X-Fern-SDK-Version": "0.5.0",
                "User-Agent": "@origoid/sdk/0.5.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.GetImssEmploymentStatusRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.Envelope.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrigoidApi.UnauthorizedError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new OrigoidApi.TooManyRequestsError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OrigoidApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrigoidApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrigoidApiTimeoutError(
                    "Timeout exceeded when calling POST /mex/social-security/v1/imss-employment-status.",
                );
            case "unknown":
                throw new errors.OrigoidApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * **Credits:** 1 per call.
     *
     * Retrieves a government worker's full ISSSTE record by CURP — personal data, affiliation, pension regime, positions, contribution history, address, assigned clinic, and the official PDF (always included as base64 in `data.files[]` (kind `document`)).
     *
     * A retrieved record returns `type: SUCCESS` for an active worker. `PENSIONER`, `SCHOLAR`, `INACTIVE`, and `DECEASED` flag KYC-material standings; when more than one applies, precedence is `DECEASED` > `PENSIONER`/`SCHOLAR` > `INACTIVE`. The raw affiliation status and beneficiary type are always in `data.affiliation`, so new statuses ISSSTE may report never break the contract. `CURP_NOT_FOUND` when the CURP has no ISSSTE record. Dates are ISO `YYYY-MM-DD`; monetary amounts are strings (MXN).
     *
     * **Field presence:** every field is always present (stable contract) — absent values are `null` (objects/scalars, including empty source strings normalized to `null`) or `[]` (arrays), never omitted. Examples: `pensions` and `family` are `[]` when the worker has none; `terminationDate` and a history row's `endDate` are `null` while ongoing; binary assets in `data.files[]` follow array semantics — only assets actually produced are listed (absent ones omitted, not `null`). Unmigrated placeholder values from ISSSTE (e.g. address `POR ACTUALIZAR`, clinic `FAVOR DE ATENDER A ESTE TRABAJADOR` / clave `0409999`, state `ENTIDAD DESCONOCIDA`) are normalized to `null` (data not yet migrated). ISSSTE only exposes records for titulares (TRABAJADOR/PENSIONISTA/BECARIO); a CURP that is only a dependant (not a titular) returns `CURP_NOT_FOUND`. To retrieve a dependant, query the titular CURP and match `data.family[]` by the dependant CURP. `beneficiaryType` is derived authoritatively from the record (a DIRECT pension means PENSIONISTA even if the document labels them TRABAJADOR); each pension carries a derived `category` (DIRECT/SURVIVOR/INSURANCE/DISABILITY).
     *
     * @param {OrigoidApi.GetIssteRecordRequest} request
     * @param {SocialSecurity.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrigoidApi.UnauthorizedError}
     * @throws {@link OrigoidApi.TooManyRequestsError}
     *
     * @example
     *     await client.socialSecurity.getIssteRecord({
     *         curp: "GOTM850312MDFMRX05"
     *     })
     */
    public getIssteRecord(
        request: OrigoidApi.GetIssteRecordRequest,
        requestOptions?: SocialSecurity.RequestOptions,
    ): core.HttpResponsePromise<OrigoidApi.GetIssteRecordResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getIssteRecord(request, requestOptions));
    }

    private async __getIssteRecord(
        request: OrigoidApi.GetIssteRecordRequest,
        requestOptions?: SocialSecurity.RequestOptions,
    ): Promise<core.WithRawResponse<OrigoidApi.GetIssteRecordResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrigoidApiEnvironment.Default,
                "mex/social-security/v1/issste-records",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@origoid/sdk",
                "X-Fern-SDK-Version": "0.5.0",
                "User-Agent": "@origoid/sdk/0.5.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.GetIssteRecordRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.GetIssteRecordResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrigoidApi.UnauthorizedError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new OrigoidApi.TooManyRequestsError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OrigoidApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrigoidApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrigoidApiTimeoutError(
                    "Timeout exceeded when calling POST /mex/social-security/v1/issste-records.",
                );
            case "unknown":
                throw new errors.OrigoidApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
