/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OrigoidApi from "../../../../api/index";
import * as core from "../../../../core";
import { IssteRecordData } from "../../../types/IssteRecordData";
import { EnvelopeStatus } from "../../../types/EnvelopeStatus";
import { ErrorDetail } from "../../../types/ErrorDetail";

export const GetIssteRecordResponse: core.serialization.ObjectSchema<
    serializers.GetIssteRecordResponse.Raw,
    OrigoidApi.GetIssteRecordResponse
> = core.serialization.object({
    data: IssteRecordData.optional(),
    status: EnvelopeStatus,
    type: core.serialization.string(),
    message: core.serialization.string(),
    errors: core.serialization.list(ErrorDetail).optional(),
    transactionId: core.serialization.string(),
    processedAt: core.serialization.date(),
    billable: core.serialization.boolean(),
});

export declare namespace GetIssteRecordResponse {
    export interface Raw {
        data?: IssteRecordData.Raw | null;
        status: EnvelopeStatus.Raw;
        type: string;
        message: string;
        errors?: ErrorDetail.Raw[] | null;
        transactionId: string;
        processedAt: string;
        billable: boolean;
    }
}
