/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OrigoidApi from "../../../../api/index";
import * as core from "../../../../core";
import { LivenessData } from "../../../types/LivenessData";
import { EnvelopeStatus } from "../../../types/EnvelopeStatus";
import { ErrorDetail } from "../../../types/ErrorDetail";

export const CheckLivenessResponse: core.serialization.ObjectSchema<
    serializers.CheckLivenessResponse.Raw,
    OrigoidApi.CheckLivenessResponse
> = core.serialization.object({
    data: LivenessData.optionalNullable(),
    status: EnvelopeStatus,
    type: core.serialization.string(),
    message: core.serialization.string(),
    errors: core.serialization.list(ErrorDetail).optional(),
    transactionId: core.serialization.string(),
    processedAt: core.serialization.date(),
    billable: core.serialization.boolean(),
});

export declare namespace CheckLivenessResponse {
    export interface Raw {
        data?: (LivenessData.Raw | null) | null;
        status: EnvelopeStatus.Raw;
        type: string;
        message: string;
        errors?: ErrorDetail.Raw[] | null;
        transactionId: string;
        processedAt: string;
        billable: boolean;
    }
}
