/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OrigoidApi from "../../../../api/index";
import * as core from "../../../../core";

export const MatchFacesRequestDocumentType: core.serialization.Schema<
    serializers.MatchFacesRequestDocumentType.Raw,
    OrigoidApi.MatchFacesRequestDocumentType
> = core.serialization.enum_(["IFE", "INE", "MEX_PASSPORT", "MEX_RESIDENCE_CARD", "MEX_PROFESSIONAL_ID", "ANY"]);

export declare namespace MatchFacesRequestDocumentType {
    export type Raw = "IFE" | "INE" | "MEX_PASSPORT" | "MEX_RESIDENCE_CARD" | "MEX_PROFESSIONAL_ID" | "ANY";
}
