/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const SearchOfacRequest: core.serialization.Schema<
    serializers.SearchOfacRequest.Raw,
    OrigoidApi.SearchOfacRequest
> = core.serialization.object({
    name: core.serialization.string(),
    minSimilarityScore: core.serialization.number().optional(),
});

export declare namespace SearchOfacRequest {
    export interface Raw {
        name: string;
        minSimilarityScore?: number | null;
    }
}
