/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const LookupNssRequest: core.serialization.Schema<
    serializers.LookupNssRequest.Raw,
    OrigoidApi.LookupNssRequest
> = core.serialization.object({
    curp: core.serialization.string(),
});

export declare namespace LookupNssRequest {
    export interface Raw {
        curp: string;
    }
}
