/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as OrigoidApi from "../../../index";
import * as serializers from "../../../../serialization/index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Renapo {
    export interface Options {
        environment?: core.Supplier<environments.OrigoidApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

/**
 * Official identity and CURP validation.
 */
export class Renapo {
    constructor(protected readonly _options: Renapo.Options) {}

    /**
     * **Credits:** 1 per call.
     *
     * Validates a CURP (Clave Única de Registro de Población) against the official RENAPO registry and returns the full personal record associated with it: given names, surnames, gender, date of birth, birth state, document status (active, deceased, apocryphal, judicial suspension), and registration metadata.
     *
     * Optionally generates the associated 13-character RFC (Registro Federal de Contribuyentes) when `generateRfc: true` is sent. RFC generation is deterministic from CURP and does not call SAT.
     *
     * Use this endpoint when you have a CURP and need to confirm it is genuine, find out who owns it, or detect if the holder is deceased before extending a financial product.
     *
     * @param {OrigoidApi.ValidateCurpRequest} request
     * @param {Renapo.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrigoidApi.UnauthorizedError}
     * @throws {@link OrigoidApi.TooManyRequestsError}
     *
     * @example
     *     await client.renapo.validateCurp({
     *         curp: "TEST900101HDFRRN09"
     *     })
     */
    public validateCurp(
        request: OrigoidApi.ValidateCurpRequest,
        requestOptions?: Renapo.RequestOptions,
    ): core.HttpResponsePromise<OrigoidApi.Envelope> {
        return core.HttpResponsePromise.fromPromise(this.__validateCurp(request, requestOptions));
    }

    private async __validateCurp(
        request: OrigoidApi.ValidateCurpRequest,
        requestOptions?: Renapo.RequestOptions,
    ): Promise<core.WithRawResponse<OrigoidApi.Envelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrigoidApiEnvironment.Default,
                "mex/renapo/v1/curp-validations",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@origoid/sdk",
                "X-Fern-SDK-Version": "0.1.0",
                "User-Agent": "@origoid/sdk/0.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.ValidateCurpRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.Envelope.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrigoidApi.UnauthorizedError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new OrigoidApi.TooManyRequestsError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OrigoidApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrigoidApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrigoidApiTimeoutError(
                    "Timeout exceeded when calling POST /mex/renapo/v1/curp-validations.",
                );
            case "unknown":
                throw new errors.OrigoidApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * **Credits:** 2 per call.
     *
     * Reconstructs a CURP from the four official input fields: given names, first surname, second surname, gender, date of birth, and birth state code. Calls RENAPO and returns the matching CURP plus the full personal record (same shape as `validateCurp`).
     *
     * Use this endpoint when your KYC form collects names and date of birth but not the CURP, and you need the CURP to file a financial product or report to regulators. The lookup uses RENAPO's strict matching — if any field is misspelled, no match is returned (`CURP_NOT_FOUND`).
     *
     * @param {OrigoidApi.LookupCurpRequest} request
     * @param {Renapo.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrigoidApi.UnauthorizedError}
     * @throws {@link OrigoidApi.TooManyRequestsError}
     *
     * @example
     *     await client.renapo.lookupCurp({
     *         givenNames: "JUAN",
     *         firstSurname: "PEREZ",
     *         dateOfBirth: "1990-01-01",
     *         gender: "H",
     *         birthStateCode: "DF"
     *     })
     */
    public lookupCurp(
        request: OrigoidApi.LookupCurpRequest,
        requestOptions?: Renapo.RequestOptions,
    ): core.HttpResponsePromise<OrigoidApi.Envelope> {
        return core.HttpResponsePromise.fromPromise(this.__lookupCurp(request, requestOptions));
    }

    private async __lookupCurp(
        request: OrigoidApi.LookupCurpRequest,
        requestOptions?: Renapo.RequestOptions,
    ): Promise<core.WithRawResponse<OrigoidApi.Envelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrigoidApiEnvironment.Default,
                "mex/renapo/v1/curp-lookups",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@origoid/sdk",
                "X-Fern-SDK-Version": "0.1.0",
                "User-Agent": "@origoid/sdk/0.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.LookupCurpRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.Envelope.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrigoidApi.UnauthorizedError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new OrigoidApi.TooManyRequestsError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OrigoidApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrigoidApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrigoidApiTimeoutError(
                    "Timeout exceeded when calling POST /mex/renapo/v1/curp-lookups.",
                );
            case "unknown":
                throw new errors.OrigoidApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
