/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as OrigoidApi from "../../../index";
import * as serializers from "../../../../serialization/index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Compliance {
    export interface Options {
        environment?: core.Supplier<environments.OrigoidApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

/**
 * Sanctions and risk lists: SAT 69, SAT 69-B, OFAC, and PEPs.
 */
export class Compliance {
    constructor(protected readonly _options: Compliance.Options) {}

    /**
     * **Credits:** 1 per call.
     *
     * Validates if an individual or legal entity is listed in the Mexican Tax Authority (SAT) Article 69 blacklist. This endpoint covers all sub-lists of Art. 69. Note: This endpoint does NOT evaluate Article 69-B (EFOS/simulated operations).
     *
     * **Business Rules (Search Priority):**
     * 1. The client must provide EITHER a name (`name` / Razón Social) OR an exact identifier (`rfc`).
     * 2. If `rfc` is provided, the backend performs a strict exact match. If only `name` is provided, the backend performs a highly restrictive text search.
     *
     * **Risk Level Matrix (`riskLevel`):**
     * - `NONE`: No matches found. Safe for automated approval.
     * - `LOW` (Informativo / Sin Riesgo Operativo): The subject has historical or administrative records but is legally operating. **Lists:** Condonados (Todos los decretos/artículos), Reducción Art. 74 CFF, Retorno de Inversiones, Entes Públicos y de Gobierno Omisos.
     * - `MEDIUM` (Riesgo Financiero / Morosidad): The subject has active enforceable debts or the SAT declared them insolvent/uncollectible. **Lists:** Firmes, Exigibles, Cancelados (Incosteabilidad / Insolvencia).
     * - `HIGH` (Riesgo Operativo Grave): The subject cannot be found by authorities or their digital billing seals (CSD) have been revoked, halting their operations. **Lists:** No Localizados, CSD Sin Efectos.
     * - `CRITICAL` (Riesgo Legal / Fraude Penal): The subject has criminal convictions related to tax crimes. **Lists:** Sentencias.
     *
     * @param {OrigoidApi.SearchSat69Request} request
     * @param {Compliance.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrigoidApi.UnauthorizedError}
     * @throws {@link OrigoidApi.TooManyRequestsError}
     *
     * @example
     *     await client.compliance.searchSat69({
     *         "name": "JUAN PEREZ LOPEZ"
     *     })
     *
     * @example
     *     await client.compliance.searchSat69({
     *         "rfc": "PELJ900101AAA"
     *     })
     */
    public searchSat69(
        request: OrigoidApi.SearchSat69Request,
        requestOptions?: Compliance.RequestOptions,
    ): core.HttpResponsePromise<OrigoidApi.Envelope> {
        return core.HttpResponsePromise.fromPromise(this.__searchSat69(request, requestOptions));
    }

    private async __searchSat69(
        request: OrigoidApi.SearchSat69Request,
        requestOptions?: Compliance.RequestOptions,
    ): Promise<core.WithRawResponse<OrigoidApi.Envelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrigoidApiEnvironment.Default,
                "mex/compliance/v1/sat-69-searches",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@origoid/sdk",
                "X-Fern-SDK-Version": "0.1.0",
                "User-Agent": "@origoid/sdk/0.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.SearchSat69Request.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.Envelope.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrigoidApi.UnauthorizedError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new OrigoidApi.TooManyRequestsError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OrigoidApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrigoidApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrigoidApiTimeoutError(
                    "Timeout exceeded when calling POST /mex/compliance/v1/sat-69-searches.",
                );
            case "unknown":
                throw new errors.OrigoidApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * **Credits:** 1 per call.
     *
     * Validates if an individual or legal entity is listed in the Mexican Tax Authority (SAT) Article 69-B blacklist. This list is specifically for EFOS (Empresas que Facturan Operaciones Simuladas), commonly known as 'Factureros' or shell companies involved in tax fraud and money laundering.
     *
     * **Business Rules (Search Priority):**
     * 1. The client must provide EITHER a name (`name` / Razón Social) OR an exact identifier (`rfc`).
     * 2. If `rfc` is provided, the backend performs a strict exact match. If only `name` is provided, the backend performs a highly restrictive text search.
     *
     * **Risk Level Matrix (`riskLevel` mapped to SAT Status):**
     * - `NONE`: No matches found in the SAT 69-B list. Safe for automated approval.
     * - `LOW`: The SAT status is **'Desvirtuado'** (Investigated but successfully proved innocence) or **'Sentencia Favorable'** (Won in court / cleared). Provided for audit trails and historical record.
     * - `MEDIUM`: Reserved for intermediate risk states. Currently not produced by the SAT 69-B classification.
     * - `HIGH`: The SAT status is **'Presunto'** (Currently under investigation for simulated operations). Extreme caution advised; usually triggers Enhanced Due Diligence (EDD) or temporal blocks.
     * - `CRITICAL`: The SAT status is **'Definitivo'** (Confirmed shell company / EFOS). Legally binding block required for AML compliance.
     *
     * @param {OrigoidApi.SearchSat69BRequest} request
     * @param {Compliance.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrigoidApi.UnauthorizedError}
     * @throws {@link OrigoidApi.TooManyRequestsError}
     *
     * @example
     *     await client.compliance.searchSat69B({
     *         "name": "JUAN PEREZ LOPEZ"
     *     })
     *
     * @example
     *     await client.compliance.searchSat69B({
     *         "rfc": "PELJ900101AAA"
     *     })
     */
    public searchSat69B(
        request: OrigoidApi.SearchSat69BRequest,
        requestOptions?: Compliance.RequestOptions,
    ): core.HttpResponsePromise<OrigoidApi.Envelope> {
        return core.HttpResponsePromise.fromPromise(this.__searchSat69B(request, requestOptions));
    }

    private async __searchSat69B(
        request: OrigoidApi.SearchSat69BRequest,
        requestOptions?: Compliance.RequestOptions,
    ): Promise<core.WithRawResponse<OrigoidApi.Envelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrigoidApiEnvironment.Default,
                "mex/compliance/v1/sat-69b-searches",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@origoid/sdk",
                "X-Fern-SDK-Version": "0.1.0",
                "User-Agent": "@origoid/sdk/0.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.SearchSat69BRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.Envelope.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrigoidApi.UnauthorizedError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new OrigoidApi.TooManyRequestsError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OrigoidApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrigoidApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrigoidApiTimeoutError(
                    "Timeout exceeded when calling POST /mex/compliance/v1/sat-69b-searches.",
                );
            case "unknown":
                throw new errors.OrigoidApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * **Credits:** 1 per call.
     *
     * Searches the official OFAC sanctions lists (SDN, Non-SDN, FSE, NS-ISA, SSI, CAPTA, NS-PLC) for the provided name or identifier. Returns matches with the originating list, sanction programs (CUBA, IRAN, RUSSIA, etc.), entity type (individual, entity, vessel, aircraft), and risk level.
     *
     * Use this endpoint as part of mandatory AML compliance to detect counterparties subject to United States sanctions before extending financial services. Required by CNBV for regulated financial institutions and recommended for any cross-border activity.
     *
     * @param {OrigoidApi.SearchOfacRequest} request
     * @param {Compliance.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrigoidApi.UnauthorizedError}
     * @throws {@link OrigoidApi.TooManyRequestsError}
     *
     * @example
     *     await client.compliance.searchOfac({
     *         name: "JOAQUIN GUZMAN LOERA"
     *     })
     */
    public searchOfac(
        request: OrigoidApi.SearchOfacRequest,
        requestOptions?: Compliance.RequestOptions,
    ): core.HttpResponsePromise<OrigoidApi.Envelope> {
        return core.HttpResponsePromise.fromPromise(this.__searchOfac(request, requestOptions));
    }

    private async __searchOfac(
        request: OrigoidApi.SearchOfacRequest,
        requestOptions?: Compliance.RequestOptions,
    ): Promise<core.WithRawResponse<OrigoidApi.Envelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrigoidApiEnvironment.Default,
                "global/compliance/v1/ofac-searches",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@origoid/sdk",
                "X-Fern-SDK-Version": "0.1.0",
                "User-Agent": "@origoid/sdk/0.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.SearchOfacRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.Envelope.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrigoidApi.UnauthorizedError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new OrigoidApi.TooManyRequestsError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OrigoidApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrigoidApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrigoidApiTimeoutError(
                    "Timeout exceeded when calling POST /global/compliance/v1/ofac-searches.",
                );
            case "unknown":
                throw new errors.OrigoidApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * **Credits:** 1 per call.
     *
     * Searches for the subject in our consolidated PEP (Politically Exposed Persons) database — including active PEPs, former PEPs (EX_PEP), and their immediate family and close associates (PEP_AFFINITY, EX_PEP_AFFINITY). Accepts full name, CURP, or RFC for matching.
     *
     * Returns each match with the political position held, institution, status (active/inactive), country, and risk level. Use this endpoint as part of enhanced due diligence for clients in regulated financial products (LFPIORPI requirements).
     *
     * @param {OrigoidApi.SearchPepsRequest} request
     * @param {Compliance.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrigoidApi.UnauthorizedError}
     * @throws {@link OrigoidApi.TooManyRequestsError}
     *
     * @example
     *     await client.compliance.searchPeps({
     *         "givenNames": "JUAN",
     *         "firstSurname": "PEREZ",
     *         "secondSurname": "LOPEZ"
     *     })
     *
     * @example
     *     await client.compliance.searchPeps({
     *         "curp": "PELJ900101HDFRRN09"
     *     })
     *
     * @example
     *     await client.compliance.searchPeps({
     *         "rfc": "PELJ900101AAA"
     *     })
     */
    public searchPeps(
        request: OrigoidApi.SearchPepsRequest,
        requestOptions?: Compliance.RequestOptions,
    ): core.HttpResponsePromise<OrigoidApi.Envelope> {
        return core.HttpResponsePromise.fromPromise(this.__searchPeps(request, requestOptions));
    }

    private async __searchPeps(
        request: OrigoidApi.SearchPepsRequest,
        requestOptions?: Compliance.RequestOptions,
    ): Promise<core.WithRawResponse<OrigoidApi.Envelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrigoidApiEnvironment.Default,
                "mex/compliance/v1/peps-searches",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@origoid/sdk",
                "X-Fern-SDK-Version": "0.1.0",
                "User-Agent": "@origoid/sdk/0.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.SearchPepsRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.Envelope.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrigoidApi.UnauthorizedError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new OrigoidApi.TooManyRequestsError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OrigoidApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrigoidApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrigoidApiTimeoutError(
                    "Timeout exceeded when calling POST /mex/compliance/v1/peps-searches.",
                );
            case "unknown":
                throw new errors.OrigoidApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
