/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         curp: "GARM900101HDFRZA01",
 *         nss: "92038109713"
 *     }
 *
 * @example
 *     {
 *         curp: "GARM900101HDFRZA01",
 *         nss: "92038109713"
 *     }
 *
 * @example
 *     {
 *         curp: "GARM900101HDFRZA01",
 *         nss: "92038109713"
 *     }
 *
 * @example
 *     {
 *         curp: "GARM900101HDFRZA01",
 *         nss: "92038109713"
 *     }
 *
 * @example
 *     {
 *         curp: "GARM900101HDFRZA01",
 *         nss: "92038109713"
 *     }
 *
 * @example
 *     {
 *         curp: "GARM900101HDFRZA01",
 *         nss: "92038109713"
 *     }
 *
 * @example
 *     {
 *         curp: "GARM900101HDFRZA01",
 *         nss: "92038109713"
 *     }
 */
export interface GetImssEmploymentStatusRequest {
    curp: string;
    nss: string;
}
