/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         curp: "GOTM850312MDFMRX05"
 *     }
 *
 * @example
 *     {
 *         curp: "GOTM850312MDFMRX05"
 *     }
 *
 * @example
 *     {
 *         curp: "GOTM850312MDFMRX05"
 *     }
 *
 * @example
 *     {
 *         curp: "GOTM850312MDFMRX05"
 *     }
 *
 * @example
 *     {
 *         curp: "GOTM850312MDFMRX05"
 *     }
 *
 * @example
 *     {
 *         curp: "GOTM850312MDFMRX05"
 *     }
 *
 * @example
 *     {
 *         curp: "GOTM850312MDFMRX05"
 *     }
 *
 * @example
 *     {
 *         curp: "GOTM850312MDFMRX05"
 *     }
 *
 * @example
 *     {
 *         curp: "GOTM850312MDFMRX05"
 *     }
 */
export interface GetIssteRecordRequest {
    /** CURP of the government worker whose ISSSTE record is requested. */
    curp: string;
}
