/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         curp: "ALMR900805HDFRZA09"
 *     }
 *
 * @example
 *     {
 *         curp: "ALMR900805HDFRZA09"
 *     }
 *
 * @example
 *     {
 *         curp: "ALMR900805HDFRZA09"
 *     }
 *
 * @example
 *     {
 *         curp: "ALMR900805HDFRZA09"
 *     }
 *
 * @example
 *     {
 *         curp: "ALMR900805HDFRZA09"
 *     }
 *
 * @example
 *     {
 *         curp: "ALMR900805HDFRZA09"
 *     }
 *
 * @example
 *     {
 *         curp: "ALMR900805HDFRZA09"
 *     }
 *
 * @example
 *     {
 *         curp: "ALMR900805HDFRZA09"
 *     }
 */
export interface LookupImssNssRequest {
    curp: string;
}
