/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Binary asset (image or document) returned inline as base64. The `files` array contains ONLY assets actually produced; an expected-but-unavailable asset is omitted (never null inside the array).
 */
export interface Asset {
    /** Semantic asset name (e.g. document, face, signature). */
    kind: string;
    /** MIME type (e.g. application/pdf, image/jpeg, application/xml). */
    contentType: string;
    /** Decoded size in bytes. */
    sizeBytes: number;
    /** Base64-encoded bytes. */
    content: string;
}
