/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Transfer lifecycle timestamps, ISO 8601 in `America/Mexico_City` (`-06:00`), second precision. Null where not applicable to the result.
 */
export interface CepValidationDataTimeline {
    /** Instant the transfer was operated (from the CEP). */
    operatedAt?: Date | null;
    /** Instant SPEI received the payment order. */
    receivedAt?: Date | null;
    /** Instant SPEI settled the payment (liquidación). */
    settledAt?: Date | null;
    /** Instant the return order was received. */
    returnReceivedAt?: Date | null;
    /** Instant the return was settled. */
    returnSettledAt?: Date | null;
}
