/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

/**
 * Transfer amount. `value` is a decimal string, exact to the cent; currency is always MXN.
 */
export interface CepValidationDataAmount {
    value?: string;
    currency?: OrigoidApi.CepValidationDataAmountCurrency;
}
