/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Inferred from the account number (18-digit CLABE or 16-digit card).
 */
export type CepValidationDataSenderAccountType = "CLABE" | "CARD";
export const CepValidationDataSenderAccountType = {
    Clabe: "CLABE",
    Card: "CARD",
} as const;
