/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CepValidationDataAmountCurrency = "MXN";
export const CepValidationDataAmountCurrency = {
    Mxn: "MXN",
} as const;
