/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

/**
 * Verified SPEI transfer details from the CEP. Null for non-located outcomes (`CEP_NOT_FOUND`) and error types.
 */
export interface CepValidationData {
    /** Whether the transfer is a confirmed, settled payment. True for LIQUIDADO; false for returned, cancelled or in-process. */
    valid?: boolean;
    /** Raw Banxico payment state. Known values: `LIQUIDADO`, `DEVUELTO`, `CANCELADO`, `EN PROCESO`. Branch on `type`; use this for display. */
    banxicoStatus?: string;
    /** Clave de rastreo of the transfer. */
    trackingKey?: string;
    /** Reference number, when present in the CEP. */
    referenceNumber?: string | null;
    /** Business operation date (ISO `YYYY-MM-DD`). The calendar date used to match; see `timeline.operatedAt` for the exact instant. */
    operationDate?: string;
    /** Payment concept, when present. */
    concept?: string | null;
    /** Transfer amount. `value` is a decimal string, exact to the cent; currency is always MXN. */
    amount?: OrigoidApi.CepValidationDataAmount;
    /** Ordering (sender) party. Fields may be null when Banxico does not expose them (for non-settled results). */
    sender?: OrigoidApi.CepValidationDataSender | null;
    /** Beneficiary party. Fields may be null when Banxico does not expose them (for non-settled results). */
    beneficiary?: OrigoidApi.CepValidationDataBeneficiary | null;
    /** Transfer lifecycle timestamps, ISO 8601 in `America/Mexico_City` (`-06:00`), second precision. Null where not applicable to the result. */
    timeline?: OrigoidApi.CepValidationDataTimeline;
    /** SPEI / Banxico cryptographic proof carried by the CEP (the digital signature that makes the CEP verifiable). */
    spei?: OrigoidApi.CepValidationDataSpei;
    /** CEP documents as inline base64 assets. The XML (`application/xml`) is present for settled payments; the PDF (`application/pdf`) is included only when `includePdf` is true. Empty for non-settled results. */
    files?: OrigoidApi.Asset[];
}
