/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * SPEI / Banxico cryptographic proof carried by the CEP (the digital signature that makes the CEP verifiable).
 */
export interface CepValidationDataSpei {
    /** Clave SPEI (operating-institution code). */
    speiKey?: string | null;
    certificateNumber?: string | null;
    /** Base64 digital signature from Banxico. */
    signature?: string | null;
    /** Original signed CDA chain (the string Banxico signed). */
    cdaChain?: string | null;
}
