/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

/**
 * Ordering (sender) party. Fields may be null when Banxico does not expose them (for non-settled results).
 */
export interface CepValidationDataSender {
    name?: string | null;
    /** Banxico institution code (5 digits). */
    bankCode?: string | null;
    bankName?: string | null;
    account?: string | null;
    /** Inferred from the account number (18-digit CLABE or 16-digit card). */
    accountType?: OrigoidApi.CepValidationDataSenderAccountType | null;
    /** RFC as printed in the CEP, when present. */
    rfc?: string | null;
}
