/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * High-level outcome. `OK` means the request was successfully processed (regardless of business result). `ERROR` means the request was rejected or could not be processed.
 */
export type EnvelopeStatus = "OK" | "ERROR";
export const EnvelopeStatus = {
    Ok: "OK",
    Error: "ERROR",
} as const;
