/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

export interface Envelope {
    status: OrigoidApi.EnvelopeStatus;
    /** Stable result type code. Includes generic codes (`SUCCESS`, `INVALID_REQUEST`, `UNAUTHORIZED`, `SERVICE_UNAVAILABLE`, `INTERNAL_ERROR`, `RATE_LIMIT_EXCEEDED`) plus endpoint-specific result codes — see this endpoint's response examples. */
    type: string;
    /** Human-readable summary of the result. Always in English (per Language Conventions in the API overview). */
    message: string;
    /** Response payload. `null` on error responses. Shape depends on the endpoint — see each operation's response schema. */
    data?: Record<string, unknown> | null;
    /** Per-field error details. Present only on `INVALID_REQUEST` responses. */
    errors?: OrigoidApi.ErrorDetail[];
    /** Unique identifier of this request, generated by the API Gateway. Propagated end-to-end for traceability. */
    transactionId: string;
    /** ISO 8601 datetime with Mexico City offset (`-06:00`). Always set by the API Gateway when the response leaves the system. */
    processedAt: Date;
    /** Whether this request will be charged against the client's plan. Typically `true` for successful business results and `false` for validation errors or system errors that prevented processing. */
    billable: boolean;
}
