/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ErrorDetail {
    /** JSON path or field name where the validation failed. Use `requestBody` for top-level errors. */
    field: string;
    /** Machine-readable error code. Examples: `MISSING_REQUIRED_FIELD`, `INVALID_FORMAT`, `INVALID_VALUE`, `INVALID_ENUM_VALUE`. */
    code: string;
    /** Human-readable description of the field-level error. */
    message: string;
}
