/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

/**
 * Face-match result. Null for `INVALID_REQUEST` and `INTERNAL_ERROR`.
 */
export interface FaceMatchData {
    /** Similarity 0-100. Null when the score was not the basis of the result (DOCUMENT_MISMATCH, NO_DOCUMENT_DETECTED, NO_FACE_DETECTED, MULTIPLE_FACES_DETECTED) — anti-leak of signal. */
    faceMatchScore?: number | null;
    isMatch?: boolean;
    /** Threshold used for the decision. Null when not applied (non-match outcomes). */
    thresholdApplied?: number | null;
    /** Document type classified from the front image (e.g. `INE`, `MEX_PASSPORT`, `OTHER`). Null in some non-match cases. */
    detectedDocumentType?: string | null;
    /** Quality/attribute labels of the selfie face (DX-friendly, no raw scores). Null when there is no single selfie face (NO_FACE_DETECTED on selfie, MULTIPLE_FACES_DETECTED). */
    selfieAnalysis?: OrigoidApi.FaceMatchDataSelfieAnalysis | null;
}
