/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

/**
 * Quality/attribute labels of the selfie face (DX-friendly, no raw scores). Null when there is no single selfie face (NO_FACE_DETECTED on selfie, MULTIPLE_FACES_DETECTED).
 */
export interface FaceMatchDataSelfieAnalysis {
    imageQuality?: OrigoidApi.FaceMatchDataSelfieAnalysisImageQuality;
    detectionConfidence?: OrigoidApi.FaceMatchDataSelfieAnalysisDetectionConfidence;
    orientation?: OrigoidApi.FaceMatchDataSelfieAnalysisOrientation;
    eyesOpen?: boolean;
    mouthOpen?: boolean;
    wearingGlasses?: boolean;
    wearingSunglasses?: boolean;
    faceCovered?: boolean;
    /** Actionable retry hints. Subset of the catalog. */
    issues?: OrigoidApi.FaceMatchDataSelfieAnalysisIssuesItem[];
}
