/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FaceMatchDataSelfieAnalysisOrientation =
    | "front"
    | "looking_left"
    | "looking_right"
    | "looking_up"
    | "looking_down"
    | "tilted"
    | "sideways";
export const FaceMatchDataSelfieAnalysisOrientation = {
    Front: "front",
    LookingLeft: "looking_left",
    LookingRight: "looking_right",
    LookingUp: "looking_up",
    LookingDown: "looking_down",
    Tilted: "tilted",
    Sideways: "sideways",
} as const;
