/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FaceMatchDataSelfieAnalysisIssuesItem =
    | "wearing_glasses"
    | "wearing_sunglasses"
    | "face_covered"
    | "eyes_closed"
    | "poor_image_quality"
    | "not_facing_camera"
    | "low_detection_confidence";
export const FaceMatchDataSelfieAnalysisIssuesItem = {
    WearingGlasses: "wearing_glasses",
    WearingSunglasses: "wearing_sunglasses",
    FaceCovered: "face_covered",
    EyesClosed: "eyes_closed",
    PoorImageQuality: "poor_image_quality",
    NotFacingCamera: "not_facing_camera",
    LowDetectionConfidence: "low_detection_confidence",
} as const;
