/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FaceMatchDataSelfieAnalysisImageQuality = "excellent" | "good" | "poor";
export const FaceMatchDataSelfieAnalysisImageQuality = {
    Excellent: "excellent",
    Good: "good",
    Poor: "poor",
} as const;
