/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

/**
 * Full ISSSTE record for a government worker. Present only when `type` is `SUCCESS`.
 */
export interface IssteRecordData {
    personalInfo?: OrigoidApi.IssteRecordDataPersonalInfo;
    affiliation?: OrigoidApi.IssteRecordDataAffiliation;
    pensionRegime?: OrigoidApi.IssteRecordDataPensionRegime;
    /** Worker positions (PLAZAS TRABAJADOR). Empty for PENSIONISTA or INACTIVO without an active position. */
    employment?: OrigoidApi.IssteRecordDataEmploymentItem[];
    /** Pension records (survivor/retirement pensions, PENSIONES). Empty when none. */
    pensions?: OrigoidApi.IssteRecordDataPensionsItem[];
    /** Contribution (cotización) timeline. May be empty for `INACTIVO` without archived data. */
    contributionHistory?: OrigoidApi.IssteRecordDataContributionHistoryItem[];
    /** FOVISSSTE contribution history (housing fund) — HISTORIAL DE COTIZACIÓN FOVISSSTE. Same shape as contributionHistory; may mirror it or be a subset. */
    fovissteHistory?: OrigoidApi.IssteRecordDataFovissteHistoryItem[];
    /** Registered family members / dependants (FAMILIARES). Empty when none. */
    family?: OrigoidApi.IssteRecordDataFamilyItem[];
    /** Domicilio. */
    address?: OrigoidApi.IssteRecordDataAddress;
    /** Assigned medical unit (clínica de adscripción). */
    clinic?: OrigoidApi.IssteRecordDataClinic;
    /** Binary assets (inline base64). The document (PDF) is always present. A face is included only when the record contains a usable face; it is omitted when no face is present or its quality is too low. */
    files?: OrigoidApi.Asset[];
}
