/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

export interface IssteRecordDataPensionRegime {
    /** Years of seniority (parsed from the source `N año(s)`). `null` when not reported. */
    seniorityYears?: number | null;
    /** Raw official pension regime. */
    scheme?: OrigoidApi.IssteRecordDataPensionRegimeScheme;
}
