/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Domicilio.
 */
export interface IssteRecordDataAddress {
    street?: string;
    exteriorNumber?: string;
    interiorNumber?: string | null;
    /** Colonia. */
    neighborhood?: string;
    /** Delegación / municipio. */
    municipality?: string;
    state?: string;
    postalCode?: string;
}
