/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

export interface IssteRecordDataPersonalInfo {
    curp?: string;
    givenNames?: string;
    firstSurname?: string;
    secondSurname?: string;
    /** RFC as printed in the record. May be incomplete (10-char base without homoclave) or empty when the source PDF omits it. */
    rfc?: string;
    /** Normalized from source HOMBRE/MUJER. */
    gender?: OrigoidApi.IssteRecordDataPersonalInfoGender;
    /** ISO `YYYY-MM-DD` (normalized from source DD/MM/YYYY). */
    dateOfBirth?: string;
    /** Civil status, normalized (source prints a gender-neutral '(A)' suffix, removed here). `null` when ISSSTE does not report it. Only SOLTERO/CASADO seen in the current corpus. */
    maritalStatus?: OrigoidApi.IssteRecordDataPersonalInfoMaritalStatus | null;
    /** Social security number (NSS). */
    nss?: string;
}
