/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Medical-unit type (raw).
 */
export type IssteRecordDataClinicType = "CMF" | "UMF" | "CMFE" | "CH" | "CAF" | "HAE" | "HG" | "CMFEQ";
export const IssteRecordDataClinicType = {
    Cmf: "CMF",
    Umf: "UMF",
    Cmfe: "CMFE",
    Ch: "CH",
    Caf: "CAF",
    Hae: "HAE",
    Hg: "HG",
    Cmfeq: "CMFEQ",
} as const;
