/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IssteRecordDataEmploymentItem {
    /** Ramo / government agency. */
    agency?: string;
    /** Pagaduría. */
    payrollOffice?: string;
    startDate?: string;
    /** Salario base de cotización (MXN). */
    baseSalary?: string;
    /** Tipo de plaza/pensión (e.g. CONFIANZA, BECARIO). */
    positionType?: string;
    /** Remuneración total (MXN). */
    totalCompensation?: string;
    /** Modalidad de seguros/prestaciones (source field `modilidad` [sic] corrected to `coverage`). */
    coverage?: string;
}
