/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Raw official pension regime.
 */
export type IssteRecordDataPensionRegimeScheme =
    "CUENTAS INDIVIDUALES" | "D\u00C9CIMO TRANSITORIO" | "SIN R\u00C9GIMEN" | "";
export const IssteRecordDataPensionRegimeScheme = {
    CuentasIndividuales: "CUENTAS INDIVIDUALES",
    DecimoTransitorio: "D\u00C9CIMO TRANSITORIO",
    SinRegimen: "SIN R\u00C9GIMEN",
    Empty: "",
} as const;
