/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Normalized from source HOMBRE/MUJER.
 */
export type IssteRecordDataPersonalInfoGender = "H" | "M";
export const IssteRecordDataPersonalInfoGender = {
    H: "H",
    M: "M",
} as const;
