/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Parentesco (official raw value).
 */
export type IssteRecordDataFamilyItemRelationship =
    | "HIJO"
    | "HIJA"
    | "ESPOSO"
    | "ESPOSA"
    | "CONCUBINA"
    | "CONCUBINO"
    | "MADRE"
    | "PADRE"
    | "ABUELA"
    | "ABUELO"
    | "HIJA DE CONYUGE";
export const IssteRecordDataFamilyItemRelationship = {
    Hijo: "HIJO",
    Hija: "HIJA",
    Esposo: "ESPOSO",
    Esposa: "ESPOSA",
    Concubina: "CONCUBINA",
    Concubino: "CONCUBINO",
    Madre: "MADRE",
    Padre: "PADRE",
    Abuela: "ABUELA",
    Abuelo: "ABUELO",
    HijaDeConyuge: "HIJA DE CONYUGE",
} as const;
