/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Derived pension class from the payroll office: DIRECT (own retirement, pagaduria DIRECTOS), SURVIVOR (deudos), INSURANCE (cuenta individual aseguradora), DISABILITY (ITP/IPP).
 */
export type IssteRecordDataPensionsItemCategory = "DIRECT" | "SURVIVOR" | "INSURANCE" | "DISABILITY";
export const IssteRecordDataPensionsItemCategory = {
    Direct: "DIRECT",
    Survivor: "SURVIVOR",
    Insurance: "INSURANCE",
    Disability: "DISABILITY",
} as const;
