/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IssteRecordDataFovissteHistoryItem {
    agency?: string;
    payrollOffice?: string;
    periodType?: string;
    startDate?: string;
    endDate?: string | null;
    /** Sueldo básico (MXN). */
    baseSalary?: string;
}
