/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Authoritative standing, derived from the record: a holder of a DIRECT pension is reported as PENSIONISTA even when the source document labels them TRABAJADOR. ISSSTE only exposes titulares.
 */
export type IssteRecordDataAffiliationBeneficiaryType = "TRABAJADOR" | "PENSIONISTA" | "BECARIO";
export const IssteRecordDataAffiliationBeneficiaryType = {
    Trabajador: "TRABAJADOR",
    Pensionista: "PENSIONISTA",
    Becario: "BECARIO",
} as const;
