/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Raw official value. Empty string when not reported.
 */
export type IssteRecordDataAffiliationAffiliationStatus = "ACTIVO" | "INACTIVO" | "FINADO" | "";
export const IssteRecordDataAffiliationAffiliationStatus = {
    Activo: "ACTIVO",
    Inactivo: "INACTIVO",
    Finado: "FINADO",
    Empty: "",
} as const;
