/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Civil status, normalized (source prints a gender-neutral '(A)' suffix, removed here). `null` when ISSSTE does not report it. Only SOLTERO/CASADO seen in the current corpus.
 */
export type IssteRecordDataPersonalInfoMaritalStatus = "SOLTERO" | "CASADO" | "DIVORCIADO" | "VIUDO" | "UNION_LIBRE";
export const IssteRecordDataPersonalInfoMaritalStatus = {
    Soltero: "SOLTERO",
    Casado: "CASADO",
    Divorciado: "DIVORCIADO",
    Viudo: "VIUDO",
    UnionLibre: "UNION_LIBRE",
} as const;
