/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

export interface IssteRecordDataAffiliation {
    /** Authoritative standing, derived from the record: a holder of a DIRECT pension is reported as PENSIONISTA even when the source document labels them TRABAJADOR. ISSSTE only exposes titulares. */
    beneficiaryType?: OrigoidApi.IssteRecordDataAffiliationBeneficiaryType;
    /** Raw official value. Empty string when not reported. */
    affiliationStatus?: OrigoidApi.IssteRecordDataAffiliationAffiliationStatus;
    /** Date the worker entered federal government employment (ISO). */
    governmentEntryDate?: string | null;
    currentPositionStartDate?: string | null;
    /** `null` while `ACTIVO`; set for `INACTIVO`/`FINADO`. */
    terminationDate?: string | null;
}
