/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

export interface IssteRecordDataFamilyItem {
    curp?: string;
    firstSurname?: string;
    secondSurname?: string;
    givenNames?: string;
    /** Parentesco (official raw value). */
    relationship?: OrigoidApi.IssteRecordDataFamilyItemRelationship;
    /** Derechohabiencia status of the family member (raw). */
    status?: OrigoidApi.IssteRecordDataFamilyItemStatus;
    dateOfBirth?: string;
    /** Fecha de alta as a dependant. */
    registrationDate?: string;
}
