/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

export interface IssteRecordDataPensionsItem {
    /** Derived pension class from the payroll office: DIRECT (own retirement, pagaduria DIRECTOS), SURVIVOR (deudos), INSURANCE (cuenta individual aseguradora), DISABILITY (ITP/IPP). */
    category?: OrigoidApi.IssteRecordDataPensionsItemCategory | null;
    agency?: string;
    payrollOffice?: string;
    startDate?: string;
    pensionNumber?: string;
    /** Numeric ISSSTE pension-type code (e.g. `101` retirement, `316` survivor). 21+ codes. */
    pensionType?: string;
    /** Monthly pension amount (MXN). */
    pensionAmount?: number;
}
