/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Derechohabiencia status of the family member (raw).
 */
export type IssteRecordDataFamilyItemStatus =
    | "ACTIVO"
    | "SIN DERECHO"
    | "EN CONSERVACI\u00D3N DE DERECHOS"
    | "POSIBLE DEUDO";
export const IssteRecordDataFamilyItemStatus = {
    Activo: "ACTIVO",
    SinDerecho: "SIN DERECHO",
    EnConservacionDeDerechos: "EN CONSERVACI\u00D3N DE DERECHOS",
    PosibleDeudo: "POSIBLE DEUDO",
} as const;
