/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

/**
 * Assigned medical unit (clínica de adscripción).
 */
export interface IssteRecordDataClinic {
    /** Clave. */
    code?: string;
    /** Medical-unit type (raw). */
    type?: OrigoidApi.IssteRecordDataClinicType;
    name?: string;
    address?: string;
    issteDelegation?: string;
    /** May be `NO DISPONIBLE` or comma-separated numbers. */
    phone?: string;
}
