/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

/**
 * Liveness result. Null for `INVALID_REQUEST`, `INTERNAL_ERROR` and `SERVICE_UNAVAILABLE`. On every `OK` outcome the object is present: when nothing could be evaluated (`NO_FACE_DETECTED`, `MULTIPLE_FACES_DETECTED`, `IMAGE_UNREADABLE`) `isLive` is `false` and the remaining fields are null.
 */
export interface LivenessData {
    /** `true` when `livenessScore` reaches the decision threshold (62). Always present; `false` when the image was not evaluated. */
    isLive?: boolean;
    /** Fused anti-spoofing score, 0–100. Null when the image was not evaluated. */
    livenessScore?: number | null;
    /** Distance of the score from the decision threshold: `HIGH` 25 points or more, `MEDIUM` 10 or more, `LOW` otherwise. Null when the image was not evaluated. */
    confidence?: OrigoidApi.LivenessDataConfidence | null;
    /** Quality/attribute labels of the evaluated face — the largest face when `allowMultipleFaces` is true. Same shape as `matchFaces`. Null when the image was not evaluated or when face analysis was unavailable. */
    selfieAnalysis?: OrigoidApi.LivenessDataSelfieAnalysis | null;
}
