/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../index";

/**
 * Quality/attribute labels of the evaluated face — the largest face when `allowMultipleFaces` is true. Same shape as `matchFaces`. Null when the image was not evaluated or when face analysis was unavailable.
 */
export interface LivenessDataSelfieAnalysis {
    /** `excellent`: brightness ≥ 75 and sharpness ≥ 75 · `good`: both ≥ 50 · `poor`: otherwise (in practice, usually a dark image rather than an out-of-focus one). */
    imageQuality?: OrigoidApi.LivenessDataSelfieAnalysisImageQuality;
    /** Provider confidence that the detection is a face: `high` ≥ 95 · `medium` ≥ 80 · `low` below 80. */
    detectionConfidence?: OrigoidApi.LivenessDataSelfieAnalysisDetectionConfidence;
    /** Evaluated in order, first match wins: `sideways` abs(yaw) ≥ 25° · `looking_left` yaw ≥ 10° · `looking_right` yaw ≤ −10° · `looking_up` pitch ≥ 20° · `looking_down` pitch ≤ −20° · `tilted` abs(roll) ≥ 15° · otherwise `front`. */
    orientation?: OrigoidApi.LivenessDataSelfieAnalysisOrientation;
    /** Null when the attribute could not be determined. */
    eyesOpen?: boolean | null;
    /** Informational; never produces an issue. Null when the attribute could not be determined. */
    mouthOpen?: boolean | null;
    /** Null when the attribute could not be determined. */
    wearingGlasses?: boolean | null;
    /** Null when the attribute could not be determined. */
    wearingSunglasses?: boolean | null;
    /** Null when the attribute could not be determined. */
    faceCovered?: boolean | null;
    /** Every condition detected on the face; empty when none. All possible values: `poor_image_quality` (`imageQuality` is `poor`) · `not_facing_camera` (`orientation` is not `front`) · `eyes_closed` (`eyesOpen` is `false`) · `face_covered` (`faceCovered` is `true`) · `wearing_glasses` (`wearingGlasses` is `true`, informational) · `wearing_sunglasses` (`wearingSunglasses` is `true`) · `low_detection_confidence` (`detectionConfidence` is `low`). Retry hints, not rejection criteria. */
    issues?: OrigoidApi.LivenessDataSelfieAnalysisIssuesItem[];
}
