/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Provider confidence that the detection is a face: `high` ≥ 95 · `medium` ≥ 80 · `low` below 80.
 */
export type LivenessDataSelfieAnalysisDetectionConfidence = "high" | "medium" | "low";
export const LivenessDataSelfieAnalysisDetectionConfidence = {
    High: "high",
    Medium: "medium",
    Low: "low",
} as const;
