/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * `excellent`: brightness ≥ 75 and sharpness ≥ 75 · `good`: both ≥ 50 · `poor`: otherwise (in practice, usually a dark image rather than an out-of-focus one).
 */
export type LivenessDataSelfieAnalysisImageQuality = "excellent" | "good" | "poor";
export const LivenessDataSelfieAnalysisImageQuality = {
    Excellent: "excellent",
    Good: "good",
    Poor: "poor",
} as const;
