/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Distance of the score from the decision threshold: `HIGH` 25 points or more, `MEDIUM` 10 or more, `LOW` otherwise. Null when the image was not evaluated.
 */
export type LivenessDataConfidence = "HIGH" | "MEDIUM" | "LOW";
export const LivenessDataConfidence = {
    High: "HIGH",
    Medium: "MEDIUM",
    Low: "LOW",
} as const;
