/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Evaluated in order, first match wins: `sideways` abs(yaw) ≥ 25° · `looking_left` yaw ≥ 10° · `looking_right` yaw ≤ −10° · `looking_up` pitch ≥ 20° · `looking_down` pitch ≤ −20° · `tilted` abs(roll) ≥ 15° · otherwise `front`.
 */
export type LivenessDataSelfieAnalysisOrientation =
    "front" | "looking_left" | "looking_right" | "looking_up" | "looking_down" | "tilted" | "sideways";
export const LivenessDataSelfieAnalysisOrientation = {
    Front: "front",
    LookingLeft: "looking_left",
    LookingRight: "looking_right",
    LookingUp: "looking_up",
    LookingDown: "looking_down",
    Tilted: "tilted",
    Sideways: "sideways",
} as const;
