/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const ValidateRfcRequest: core.serialization.Schema<
    serializers.ValidateRfcRequest.Raw,
    OrigoidApi.ValidateRfcRequest
> = core.serialization.object({
    rfc: core.serialization.string(),
});

export declare namespace ValidateRfcRequest {
    export interface Raw {
        rfc: string;
    }
}
