/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Optional. Use a specific type (e.g. `INE`, `MEX_PASSPORT`) for strict validation against that exact document type. Use `ANY` to require the image be some recognized ID (auto-detected) — returns `NO_DOCUMENT_DETECTED` if not. Omit it to skip document validation.
 */
export type MatchFacesRequestDocumentType =
    | "IFE"
    | "INE"
    | "MEX_PASSPORT"
    | "MEX_RESIDENCE_CARD"
    | "MEX_PROFESSIONAL_ID"
    | "ANY";
export const MatchFacesRequestDocumentType = {
    Ife: "IFE",
    Ine: "INE",
    MexPassport: "MEX_PASSPORT",
    MexResidenceCard: "MEX_RESIDENCE_CARD",
    MexProfessionalId: "MEX_PROFESSIONAL_ID",
    Any: "ANY",
} as const;
