/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OrigoidApi from "../../../../api/index";
import * as core from "../../../../core";

export const LookupCurpRequestGender: core.serialization.Schema<
    serializers.LookupCurpRequestGender.Raw,
    OrigoidApi.LookupCurpRequestGender
> = core.serialization.enum_(["H", "M", "X"]);

export declare namespace LookupCurpRequestGender {
    export type Raw = "H" | "M" | "X";
}
