/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as OrigoidApi from "../../../index";
import * as serializers from "../../../../serialization/index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Biometrics {
    export interface Options {
        environment?: core.Supplier<environments.OrigoidApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

/**
 * Facial biometric comparison against identity documents.
 */
export class Biometrics {
    constructor(protected readonly _options: Biometrics.Options) {}

    /**
     * **Credits:** 1 per call.
     *
     * Compares two facial images and returns a similarity score (0–100) plus a binary match/no-match decision. Typical use is 1:1 verification between a live selfie and the photograph on an ID document.
     *
     * Use this endpoint to confirm that the person presenting an ID is the same person depicted on it.
     *
     * @param {OrigoidApi.MatchFacesRequest} request
     * @param {Biometrics.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrigoidApi.UnauthorizedError}
     * @throws {@link OrigoidApi.TooManyRequestsError}
     *
     * @example
     *     await client.biometrics.matchFaces({
     *         face: "face",
     *         front: "front"
     *     })
     */
    public matchFaces(
        request: OrigoidApi.MatchFacesRequest,
        requestOptions?: Biometrics.RequestOptions,
    ): core.HttpResponsePromise<OrigoidApi.MatchFacesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__matchFaces(request, requestOptions));
    }

    private async __matchFaces(
        request: OrigoidApi.MatchFacesRequest,
        requestOptions?: Biometrics.RequestOptions,
    ): Promise<core.WithRawResponse<OrigoidApi.MatchFacesResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrigoidApiEnvironment.Default,
                "global/biometrics/v1/face-matches",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@origoid/sdk",
                "X-Fern-SDK-Version": "0.2.0",
                "User-Agent": "@origoid/sdk/0.2.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.MatchFacesRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.MatchFacesResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrigoidApi.UnauthorizedError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new OrigoidApi.TooManyRequestsError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OrigoidApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrigoidApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrigoidApiTimeoutError(
                    "Timeout exceeded when calling POST /global/biometrics/v1/face-matches.",
                );
            case "unknown":
                throw new errors.OrigoidApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * **Credits:** 1 per call.
     *
     * Analyzes a selfie to determine whether it depicts a real, live person in front of the camera (`isLive: true`) or a spoofing attempt (printed photo, screen replay, mask). Returns a liveness score, confidence level, and detected attack types when applicable.
     *
     * Use this endpoint at the start of a remote KYC flow to filter out automated bots, recycled images, and basic presentation attacks before invoking heavier downstream checks.
     *
     * @param {OrigoidApi.CheckLivenessRequest} request
     * @param {Biometrics.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrigoidApi.UnauthorizedError}
     * @throws {@link OrigoidApi.TooManyRequestsError}
     *
     * @example
     *     await client.biometrics.checkLiveness({
     *         selfie: "selfie"
     *     })
     */
    public checkLiveness(
        request: OrigoidApi.CheckLivenessRequest,
        requestOptions?: Biometrics.RequestOptions,
    ): core.HttpResponsePromise<OrigoidApi.Envelope> {
        return core.HttpResponsePromise.fromPromise(this.__checkLiveness(request, requestOptions));
    }

    private async __checkLiveness(
        request: OrigoidApi.CheckLivenessRequest,
        requestOptions?: Biometrics.RequestOptions,
    ): Promise<core.WithRawResponse<OrigoidApi.Envelope>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrigoidApiEnvironment.Default,
                "global/biometrics/v1/liveness-checks",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@origoid/sdk",
                "X-Fern-SDK-Version": "0.2.0",
                "User-Agent": "@origoid/sdk/0.2.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.CheckLivenessRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.Envelope.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrigoidApi.UnauthorizedError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 429:
                    throw new OrigoidApi.TooManyRequestsError(
                        serializers.Envelope.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OrigoidApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrigoidApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrigoidApiTimeoutError(
                    "Timeout exceeded when calling POST /global/biometrics/v1/liveness-checks.",
                );
            case "unknown":
                throw new errors.OrigoidApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
