/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 *
 * @example
 *     {}
 *
 * @example
 *     {}
 *
 * @example
 *     {}
 */
export interface IssueTokenRequest {
    /** Seconds of validity (Default: 1800). */
    expireAfter?: number;
}
