/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OrigoidApi from "../../../../api/index";
import * as core from "../../../../core";

export const ExtractCsfRequest: core.serialization.Schema<
    serializers.ExtractCsfRequest.Raw,
    OrigoidApi.ExtractCsfRequest
> = core.serialization.undiscriminatedUnion([core.serialization.unknown()]);

export declare namespace ExtractCsfRequest {
    export type Raw = unknown;
}
