/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OrigoidApi from "../../../../api/index";
import * as core from "../../../../core";

export const ValidateCfdiRequest: core.serialization.Schema<
    serializers.ValidateCfdiRequest.Raw,
    OrigoidApi.ValidateCfdiRequest
> = core.serialization.undiscriminatedUnion([core.serialization.unknown()]);

export declare namespace ValidateCfdiRequest {
    export type Raw = unknown;
}
