/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Identify the transfer by its tracking key or its reference number (choose the matching request body below), and provide the beneficiary account, bank code and amount to match. When the account is an 18-digit CLABE the bank code is resolved from it automatically; for a card account, include the bank code.
 */
export type ValidateCepRequest = unknown;
