/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         back: "back"
 *     }
 *
 * @example
 *     {
 *         back: "back"
 *     }
 *
 * @example
 *     {
 *         back: "back"
 *     }
 *
 * @example
 *     {
 *         back: "back"
 *     }
 *
 * @example
 *     {
 *         back: "back"
 *     }
 *
 * @example
 *     {
 *         back: "back"
 *     }
 *
 * @example
 *     {
 *         back: "back"
 *     }
 */
export interface ExtractQrDataRequest {
    /** Back image of the INE credential in Base64 (PNG/JPG). The QR code must be visible. **Required.** */
    back: string;
}
