/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         front: "front"
 *     }
 */
export interface ExtractVoterIdDataRequest {
    /** Front image in Base64 (PNG/JPG) */
    front: string;
    /** Back image in Base64 (PNG/JPG). Optional. */
    back?: string;
}
