/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const Asset: core.serialization.ObjectSchema<serializers.Asset.Raw, OrigoidApi.Asset> =
    core.serialization.object({
        kind: core.serialization.string(),
        contentType: core.serialization.string(),
        sizeBytes: core.serialization.number(),
        content: core.serialization.string(),
    });

export declare namespace Asset {
    export interface Raw {
        kind: string;
        contentType: string;
        sizeBytes: number;
        content: string;
    }
}
