/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { CepValidationDataAmountCurrency } from "./CepValidationDataAmountCurrency";

export const CepValidationDataAmount: core.serialization.ObjectSchema<
    serializers.CepValidationDataAmount.Raw,
    OrigoidApi.CepValidationDataAmount
> = core.serialization.object({
    value: core.serialization.string().optional(),
    currency: CepValidationDataAmountCurrency.optional(),
});

export declare namespace CepValidationDataAmount {
    export interface Raw {
        value?: string | null;
        currency?: CepValidationDataAmountCurrency.Raw | null;
    }
}
