/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const CepValidationDataSenderAccountType: core.serialization.Schema<
    serializers.CepValidationDataSenderAccountType.Raw,
    OrigoidApi.CepValidationDataSenderAccountType
> = core.serialization.enum_(["CLABE", "CARD"]);

export declare namespace CepValidationDataSenderAccountType {
    export type Raw = "CLABE" | "CARD";
}
