/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { CepValidationDataAmount } from "./CepValidationDataAmount";
import { CepValidationDataSender } from "./CepValidationDataSender";
import { CepValidationDataBeneficiary } from "./CepValidationDataBeneficiary";
import { CepValidationDataTimeline } from "./CepValidationDataTimeline";
import { CepValidationDataSpei } from "./CepValidationDataSpei";
import { Asset } from "./Asset";

export const CepValidationData: core.serialization.ObjectSchema<
    serializers.CepValidationData.Raw,
    OrigoidApi.CepValidationData
> = core.serialization.object({
    valid: core.serialization.boolean().optional(),
    banxicoStatus: core.serialization.string().optional(),
    trackingKey: core.serialization.string().optional(),
    referenceNumber: core.serialization.string().optionalNullable(),
    operationDate: core.serialization.string().optional(),
    concept: core.serialization.string().optionalNullable(),
    amount: CepValidationDataAmount.optional(),
    sender: CepValidationDataSender.optionalNullable(),
    beneficiary: CepValidationDataBeneficiary.optionalNullable(),
    timeline: CepValidationDataTimeline.optional(),
    spei: CepValidationDataSpei.optional(),
    files: core.serialization.list(Asset).optional(),
});

export declare namespace CepValidationData {
    export interface Raw {
        valid?: boolean | null;
        banxicoStatus?: string | null;
        trackingKey?: string | null;
        referenceNumber?: (string | null) | null;
        operationDate?: string | null;
        concept?: (string | null) | null;
        amount?: CepValidationDataAmount.Raw | null;
        sender?: (CepValidationDataSender.Raw | null) | null;
        beneficiary?: (CepValidationDataBeneficiary.Raw | null) | null;
        timeline?: CepValidationDataTimeline.Raw | null;
        spei?: CepValidationDataSpei.Raw | null;
        files?: Asset.Raw[] | null;
    }
}
