/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const CepValidationDataAmountCurrency: core.serialization.Schema<
    serializers.CepValidationDataAmountCurrency.Raw,
    OrigoidApi.CepValidationDataAmountCurrency
> = core.serialization.enum_(["MXN"]);

export declare namespace CepValidationDataAmountCurrency {
    export type Raw = "MXN";
}
