/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const CepValidationDataTimeline: core.serialization.ObjectSchema<
    serializers.CepValidationDataTimeline.Raw,
    OrigoidApi.CepValidationDataTimeline
> = core.serialization.object({
    operatedAt: core.serialization.date().optionalNullable(),
    receivedAt: core.serialization.date().optionalNullable(),
    settledAt: core.serialization.date().optionalNullable(),
    returnReceivedAt: core.serialization.date().optionalNullable(),
    returnSettledAt: core.serialization.date().optionalNullable(),
});

export declare namespace CepValidationDataTimeline {
    export interface Raw {
        operatedAt?: (string | null) | null;
        receivedAt?: (string | null) | null;
        settledAt?: (string | null) | null;
        returnReceivedAt?: (string | null) | null;
        returnSettledAt?: (string | null) | null;
    }
}
