/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { CepValidationDataBeneficiaryAccountType } from "./CepValidationDataBeneficiaryAccountType";

export const CepValidationDataBeneficiary: core.serialization.ObjectSchema<
    serializers.CepValidationDataBeneficiary.Raw,
    OrigoidApi.CepValidationDataBeneficiary
> = core.serialization.object({
    name: core.serialization.string().optionalNullable(),
    bankCode: core.serialization.string().optionalNullable(),
    bankName: core.serialization.string().optionalNullable(),
    account: core.serialization.string().optionalNullable(),
    accountType: CepValidationDataBeneficiaryAccountType.optionalNullable(),
    rfc: core.serialization.string().optionalNullable(),
});

export declare namespace CepValidationDataBeneficiary {
    export interface Raw {
        name?: (string | null) | null;
        bankCode?: (string | null) | null;
        bankName?: (string | null) | null;
        account?: (string | null) | null;
        accountType?: (CepValidationDataBeneficiaryAccountType.Raw | null) | null;
        rfc?: (string | null) | null;
    }
}
