/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const CepValidationDataSpei: core.serialization.ObjectSchema<
    serializers.CepValidationDataSpei.Raw,
    OrigoidApi.CepValidationDataSpei
> = core.serialization.object({
    speiKey: core.serialization.string().optionalNullable(),
    certificateNumber: core.serialization.string().optionalNullable(),
    signature: core.serialization.string().optionalNullable(),
    cdaChain: core.serialization.string().optionalNullable(),
});

export declare namespace CepValidationDataSpei {
    export interface Raw {
        speiKey?: (string | null) | null;
        certificateNumber?: (string | null) | null;
        signature?: (string | null) | null;
        cdaChain?: (string | null) | null;
    }
}
