/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const CepValidationDataBeneficiaryAccountType: core.serialization.Schema<
    serializers.CepValidationDataBeneficiaryAccountType.Raw,
    OrigoidApi.CepValidationDataBeneficiaryAccountType
> = core.serialization.enum_(["CLABE", "CARD"]);

export declare namespace CepValidationDataBeneficiaryAccountType {
    export type Raw = "CLABE" | "CARD";
}
