/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { EnvelopeStatus } from "./EnvelopeStatus";
import { ErrorDetail } from "./ErrorDetail";

export const Envelope: core.serialization.ObjectSchema<serializers.Envelope.Raw, OrigoidApi.Envelope> =
    core.serialization.object({
        status: EnvelopeStatus,
        type: core.serialization.string(),
        message: core.serialization.string(),
        data: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optionalNullable(),
        errors: core.serialization.list(ErrorDetail).optional(),
        transactionId: core.serialization.string(),
        processedAt: core.serialization.date(),
        billable: core.serialization.boolean(),
    });

export declare namespace Envelope {
    export interface Raw {
        status: EnvelopeStatus.Raw;
        type: string;
        message: string;
        data?: (Record<string, unknown> | null) | null;
        errors?: ErrorDetail.Raw[] | null;
        transactionId: string;
        processedAt: string;
        billable: boolean;
    }
}
