/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const EnvelopeStatus: core.serialization.Schema<serializers.EnvelopeStatus.Raw, OrigoidApi.EnvelopeStatus> =
    core.serialization.enum_(["OK", "ERROR"]);

export declare namespace EnvelopeStatus {
    export type Raw = "OK" | "ERROR";
}
