/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const ErrorDetail: core.serialization.ObjectSchema<serializers.ErrorDetail.Raw, OrigoidApi.ErrorDetail> =
    core.serialization.object({
        field: core.serialization.string(),
        code: core.serialization.string(),
        message: core.serialization.string(),
    });

export declare namespace ErrorDetail {
    export interface Raw {
        field: string;
        code: string;
        message: string;
    }
}
