/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { FaceMatchDataSelfieAnalysisImageQuality } from "./FaceMatchDataSelfieAnalysisImageQuality";
import { FaceMatchDataSelfieAnalysisDetectionConfidence } from "./FaceMatchDataSelfieAnalysisDetectionConfidence";
import { FaceMatchDataSelfieAnalysisOrientation } from "./FaceMatchDataSelfieAnalysisOrientation";
import { FaceMatchDataSelfieAnalysisIssuesItem } from "./FaceMatchDataSelfieAnalysisIssuesItem";

export const FaceMatchDataSelfieAnalysis: core.serialization.ObjectSchema<
    serializers.FaceMatchDataSelfieAnalysis.Raw,
    OrigoidApi.FaceMatchDataSelfieAnalysis
> = core.serialization.object({
    imageQuality: FaceMatchDataSelfieAnalysisImageQuality.optional(),
    detectionConfidence: FaceMatchDataSelfieAnalysisDetectionConfidence.optional(),
    orientation: FaceMatchDataSelfieAnalysisOrientation.optional(),
    eyesOpen: core.serialization.boolean().optional(),
    mouthOpen: core.serialization.boolean().optional(),
    wearingGlasses: core.serialization.boolean().optional(),
    wearingSunglasses: core.serialization.boolean().optional(),
    faceCovered: core.serialization.boolean().optional(),
    issues: core.serialization.list(FaceMatchDataSelfieAnalysisIssuesItem).optional(),
});

export declare namespace FaceMatchDataSelfieAnalysis {
    export interface Raw {
        imageQuality?: FaceMatchDataSelfieAnalysisImageQuality.Raw | null;
        detectionConfidence?: FaceMatchDataSelfieAnalysisDetectionConfidence.Raw | null;
        orientation?: FaceMatchDataSelfieAnalysisOrientation.Raw | null;
        eyesOpen?: boolean | null;
        mouthOpen?: boolean | null;
        wearingGlasses?: boolean | null;
        wearingSunglasses?: boolean | null;
        faceCovered?: boolean | null;
        issues?: FaceMatchDataSelfieAnalysisIssuesItem.Raw[] | null;
    }
}
