/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const FaceMatchDataSelfieAnalysisDetectionConfidence: core.serialization.Schema<
    serializers.FaceMatchDataSelfieAnalysisDetectionConfidence.Raw,
    OrigoidApi.FaceMatchDataSelfieAnalysisDetectionConfidence
> = core.serialization.enum_(["high", "medium", "low"]);

export declare namespace FaceMatchDataSelfieAnalysisDetectionConfidence {
    export type Raw = "high" | "medium" | "low";
}
