/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const FaceMatchDataSelfieAnalysisOrientation: core.serialization.Schema<
    serializers.FaceMatchDataSelfieAnalysisOrientation.Raw,
    OrigoidApi.FaceMatchDataSelfieAnalysisOrientation
> = core.serialization.enum_([
    "front",
    "looking_left",
    "looking_right",
    "looking_up",
    "looking_down",
    "tilted",
    "sideways",
]);

export declare namespace FaceMatchDataSelfieAnalysisOrientation {
    export type Raw =
        "front" | "looking_left" | "looking_right" | "looking_up" | "looking_down" | "tilted" | "sideways";
}
