/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const FaceMatchDataSelfieAnalysisImageQuality: core.serialization.Schema<
    serializers.FaceMatchDataSelfieAnalysisImageQuality.Raw,
    OrigoidApi.FaceMatchDataSelfieAnalysisImageQuality
> = core.serialization.enum_(["excellent", "good", "poor"]);

export declare namespace FaceMatchDataSelfieAnalysisImageQuality {
    export type Raw = "excellent" | "good" | "poor";
}
