/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { FaceMatchDataSelfieAnalysis } from "./FaceMatchDataSelfieAnalysis";

export const FaceMatchData: core.serialization.ObjectSchema<serializers.FaceMatchData.Raw, OrigoidApi.FaceMatchData> =
    core.serialization.object({
        faceMatchScore: core.serialization.number().optionalNullable(),
        isMatch: core.serialization.boolean().optional(),
        thresholdApplied: core.serialization.number().optionalNullable(),
        detectedDocumentType: core.serialization.string().optionalNullable(),
        selfieAnalysis: FaceMatchDataSelfieAnalysis.optionalNullable(),
    });

export declare namespace FaceMatchData {
    export interface Raw {
        faceMatchScore?: (number | null) | null;
        isMatch?: boolean | null;
        thresholdApplied?: (number | null) | null;
        detectedDocumentType?: (string | null) | null;
        selfieAnalysis?: (FaceMatchDataSelfieAnalysis.Raw | null) | null;
    }
}
