/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { IssteRecordDataAffiliationBeneficiaryType } from "./IssteRecordDataAffiliationBeneficiaryType";
import { IssteRecordDataAffiliationAffiliationStatus } from "./IssteRecordDataAffiliationAffiliationStatus";

export const IssteRecordDataAffiliation: core.serialization.ObjectSchema<
    serializers.IssteRecordDataAffiliation.Raw,
    OrigoidApi.IssteRecordDataAffiliation
> = core.serialization.object({
    beneficiaryType: IssteRecordDataAffiliationBeneficiaryType.optional(),
    affiliationStatus: IssteRecordDataAffiliationAffiliationStatus.optional(),
    governmentEntryDate: core.serialization.string().optionalNullable(),
    currentPositionStartDate: core.serialization.string().optionalNullable(),
    terminationDate: core.serialization.string().optionalNullable(),
});

export declare namespace IssteRecordDataAffiliation {
    export interface Raw {
        beneficiaryType?: IssteRecordDataAffiliationBeneficiaryType.Raw | null;
        affiliationStatus?: IssteRecordDataAffiliationAffiliationStatus.Raw | null;
        governmentEntryDate?: (string | null) | null;
        currentPositionStartDate?: (string | null) | null;
        terminationDate?: (string | null) | null;
    }
}
