/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { IssteRecordDataPersonalInfo } from "./IssteRecordDataPersonalInfo";
import { IssteRecordDataAffiliation } from "./IssteRecordDataAffiliation";
import { IssteRecordDataPensionRegime } from "./IssteRecordDataPensionRegime";
import { IssteRecordDataEmploymentItem } from "./IssteRecordDataEmploymentItem";
import { IssteRecordDataPensionsItem } from "./IssteRecordDataPensionsItem";
import { IssteRecordDataContributionHistoryItem } from "./IssteRecordDataContributionHistoryItem";
import { IssteRecordDataFovissteHistoryItem } from "./IssteRecordDataFovissteHistoryItem";
import { IssteRecordDataFamilyItem } from "./IssteRecordDataFamilyItem";
import { IssteRecordDataAddress } from "./IssteRecordDataAddress";
import { IssteRecordDataClinic } from "./IssteRecordDataClinic";
import { Asset } from "./Asset";

export const IssteRecordData: core.serialization.ObjectSchema<
    serializers.IssteRecordData.Raw,
    OrigoidApi.IssteRecordData
> = core.serialization.object({
    personalInfo: IssteRecordDataPersonalInfo.optional(),
    affiliation: IssteRecordDataAffiliation.optional(),
    pensionRegime: IssteRecordDataPensionRegime.optional(),
    employment: core.serialization.list(IssteRecordDataEmploymentItem).optional(),
    pensions: core.serialization.list(IssteRecordDataPensionsItem).optional(),
    contributionHistory: core.serialization.list(IssteRecordDataContributionHistoryItem).optional(),
    fovissteHistory: core.serialization.list(IssteRecordDataFovissteHistoryItem).optional(),
    family: core.serialization.list(IssteRecordDataFamilyItem).optional(),
    address: IssteRecordDataAddress.optional(),
    clinic: IssteRecordDataClinic.optional(),
    files: core.serialization.list(Asset).optional(),
});

export declare namespace IssteRecordData {
    export interface Raw {
        personalInfo?: IssteRecordDataPersonalInfo.Raw | null;
        affiliation?: IssteRecordDataAffiliation.Raw | null;
        pensionRegime?: IssteRecordDataPensionRegime.Raw | null;
        employment?: IssteRecordDataEmploymentItem.Raw[] | null;
        pensions?: IssteRecordDataPensionsItem.Raw[] | null;
        contributionHistory?: IssteRecordDataContributionHistoryItem.Raw[] | null;
        fovissteHistory?: IssteRecordDataFovissteHistoryItem.Raw[] | null;
        family?: IssteRecordDataFamilyItem.Raw[] | null;
        address?: IssteRecordDataAddress.Raw | null;
        clinic?: IssteRecordDataClinic.Raw | null;
        files?: Asset.Raw[] | null;
    }
}
