/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const IssteRecordDataEmploymentItem: core.serialization.ObjectSchema<
    serializers.IssteRecordDataEmploymentItem.Raw,
    OrigoidApi.IssteRecordDataEmploymentItem
> = core.serialization.object({
    agency: core.serialization.string().optional(),
    payrollOffice: core.serialization.string().optional(),
    startDate: core.serialization.string().optional(),
    baseSalary: core.serialization.string().optional(),
    positionType: core.serialization.string().optional(),
    totalCompensation: core.serialization.string().optional(),
    coverage: core.serialization.string().optional(),
});

export declare namespace IssteRecordDataEmploymentItem {
    export interface Raw {
        agency?: string | null;
        payrollOffice?: string | null;
        startDate?: string | null;
        baseSalary?: string | null;
        positionType?: string | null;
        totalCompensation?: string | null;
        coverage?: string | null;
    }
}
