/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const IssteRecordDataFamilyItemRelationship: core.serialization.Schema<
    serializers.IssteRecordDataFamilyItemRelationship.Raw,
    OrigoidApi.IssteRecordDataFamilyItemRelationship
> = core.serialization.enum_([
    "HIJO",
    "HIJA",
    "ESPOSO",
    "ESPOSA",
    "CONCUBINA",
    "CONCUBINO",
    "MADRE",
    "PADRE",
    "ABUELA",
    "ABUELO",
    "HIJA DE CONYUGE",
]);

export declare namespace IssteRecordDataFamilyItemRelationship {
    export type Raw =
        | "HIJO"
        | "HIJA"
        | "ESPOSO"
        | "ESPOSA"
        | "CONCUBINA"
        | "CONCUBINO"
        | "MADRE"
        | "PADRE"
        | "ABUELA"
        | "ABUELO"
        | "HIJA DE CONYUGE";
}
