/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { IssteRecordDataFamilyItemRelationship } from "./IssteRecordDataFamilyItemRelationship";
import { IssteRecordDataFamilyItemStatus } from "./IssteRecordDataFamilyItemStatus";

export const IssteRecordDataFamilyItem: core.serialization.ObjectSchema<
    serializers.IssteRecordDataFamilyItem.Raw,
    OrigoidApi.IssteRecordDataFamilyItem
> = core.serialization.object({
    curp: core.serialization.string().optional(),
    firstSurname: core.serialization.string().optional(),
    secondSurname: core.serialization.string().optional(),
    givenNames: core.serialization.string().optional(),
    relationship: IssteRecordDataFamilyItemRelationship.optional(),
    status: IssteRecordDataFamilyItemStatus.optional(),
    dateOfBirth: core.serialization.string().optional(),
    registrationDate: core.serialization.string().optional(),
});

export declare namespace IssteRecordDataFamilyItem {
    export interface Raw {
        curp?: string | null;
        firstSurname?: string | null;
        secondSurname?: string | null;
        givenNames?: string | null;
        relationship?: IssteRecordDataFamilyItemRelationship.Raw | null;
        status?: IssteRecordDataFamilyItemStatus.Raw | null;
        dateOfBirth?: string | null;
        registrationDate?: string | null;
    }
}
