/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const IssteRecordDataPersonalInfoGender: core.serialization.Schema<
    serializers.IssteRecordDataPersonalInfoGender.Raw,
    OrigoidApi.IssteRecordDataPersonalInfoGender
> = core.serialization.enum_(["H", "M"]);

export declare namespace IssteRecordDataPersonalInfoGender {
    export type Raw = "H" | "M";
}
