/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { IssteRecordDataPensionRegimeScheme } from "./IssteRecordDataPensionRegimeScheme";

export const IssteRecordDataPensionRegime: core.serialization.ObjectSchema<
    serializers.IssteRecordDataPensionRegime.Raw,
    OrigoidApi.IssteRecordDataPensionRegime
> = core.serialization.object({
    seniorityYears: core.serialization.number().optionalNullable(),
    scheme: IssteRecordDataPensionRegimeScheme.optional(),
});

export declare namespace IssteRecordDataPensionRegime {
    export interface Raw {
        seniorityYears?: (number | null) | null;
        scheme?: IssteRecordDataPensionRegimeScheme.Raw | null;
    }
}
