/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const IssteRecordDataAddress: core.serialization.ObjectSchema<
    serializers.IssteRecordDataAddress.Raw,
    OrigoidApi.IssteRecordDataAddress
> = core.serialization.object({
    street: core.serialization.string().optional(),
    exteriorNumber: core.serialization.string().optional(),
    interiorNumber: core.serialization.string().optionalNullable(),
    neighborhood: core.serialization.string().optional(),
    municipality: core.serialization.string().optional(),
    state: core.serialization.string().optional(),
    postalCode: core.serialization.string().optional(),
});

export declare namespace IssteRecordDataAddress {
    export interface Raw {
        street?: string | null;
        exteriorNumber?: string | null;
        interiorNumber?: (string | null) | null;
        neighborhood?: string | null;
        municipality?: string | null;
        state?: string | null;
        postalCode?: string | null;
    }
}
