/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const IssteRecordDataPensionRegimeScheme: core.serialization.Schema<
    serializers.IssteRecordDataPensionRegimeScheme.Raw,
    OrigoidApi.IssteRecordDataPensionRegimeScheme
> = core.serialization.enum_(["CUENTAS INDIVIDUALES", "D\u00C9CIMO TRANSITORIO", "SIN R\u00C9GIMEN", ""]);

export declare namespace IssteRecordDataPensionRegimeScheme {
    export type Raw = "CUENTAS INDIVIDUALES" | "D\u00C9CIMO TRANSITORIO" | "SIN R\u00C9GIMEN" | "";
}
