/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { IssteRecordDataPersonalInfoGender } from "./IssteRecordDataPersonalInfoGender";
import { IssteRecordDataPersonalInfoMaritalStatus } from "./IssteRecordDataPersonalInfoMaritalStatus";

export const IssteRecordDataPersonalInfo: core.serialization.ObjectSchema<
    serializers.IssteRecordDataPersonalInfo.Raw,
    OrigoidApi.IssteRecordDataPersonalInfo
> = core.serialization.object({
    curp: core.serialization.string().optional(),
    givenNames: core.serialization.string().optional(),
    firstSurname: core.serialization.string().optional(),
    secondSurname: core.serialization.string().optional(),
    rfc: core.serialization.string().optional(),
    gender: IssteRecordDataPersonalInfoGender.optional(),
    dateOfBirth: core.serialization.string().optional(),
    maritalStatus: IssteRecordDataPersonalInfoMaritalStatus.optionalNullable(),
    nss: core.serialization.string().optional(),
});

export declare namespace IssteRecordDataPersonalInfo {
    export interface Raw {
        curp?: string | null;
        givenNames?: string | null;
        firstSurname?: string | null;
        secondSurname?: string | null;
        rfc?: string | null;
        gender?: IssteRecordDataPersonalInfoGender.Raw | null;
        dateOfBirth?: string | null;
        maritalStatus?: (IssteRecordDataPersonalInfoMaritalStatus.Raw | null) | null;
        nss?: string | null;
    }
}
