/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const IssteRecordDataPersonalInfoMaritalStatus: core.serialization.Schema<
    serializers.IssteRecordDataPersonalInfoMaritalStatus.Raw,
    OrigoidApi.IssteRecordDataPersonalInfoMaritalStatus
> = core.serialization.enum_(["SOLTERO", "CASADO", "DIVORCIADO", "VIUDO", "UNION_LIBRE"]);

export declare namespace IssteRecordDataPersonalInfoMaritalStatus {
    export type Raw = "SOLTERO" | "CASADO" | "DIVORCIADO" | "VIUDO" | "UNION_LIBRE";
}
