/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const IssteRecordDataClinicType: core.serialization.Schema<
    serializers.IssteRecordDataClinicType.Raw,
    OrigoidApi.IssteRecordDataClinicType
> = core.serialization.enum_(["CMF", "UMF", "CMFE", "CH", "CAF", "HAE", "HG", "CMFEQ"]);

export declare namespace IssteRecordDataClinicType {
    export type Raw = "CMF" | "UMF" | "CMFE" | "CH" | "CAF" | "HAE" | "HG" | "CMFEQ";
}
