/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const IssteRecordDataFamilyItemStatus: core.serialization.Schema<
    serializers.IssteRecordDataFamilyItemStatus.Raw,
    OrigoidApi.IssteRecordDataFamilyItemStatus
> = core.serialization.enum_(["ACTIVO", "SIN DERECHO", "EN CONSERVACI\u00D3N DE DERECHOS", "POSIBLE DEUDO"]);

export declare namespace IssteRecordDataFamilyItemStatus {
    export type Raw = "ACTIVO" | "SIN DERECHO" | "EN CONSERVACI\u00D3N DE DERECHOS" | "POSIBLE DEUDO";
}
