/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const IssteRecordDataAffiliationBeneficiaryType: core.serialization.Schema<
    serializers.IssteRecordDataAffiliationBeneficiaryType.Raw,
    OrigoidApi.IssteRecordDataAffiliationBeneficiaryType
> = core.serialization.enum_(["TRABAJADOR", "PENSIONISTA", "BECARIO"]);

export declare namespace IssteRecordDataAffiliationBeneficiaryType {
    export type Raw = "TRABAJADOR" | "PENSIONISTA" | "BECARIO";
}
