/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const IssteRecordDataFovissteHistoryItem: core.serialization.ObjectSchema<
    serializers.IssteRecordDataFovissteHistoryItem.Raw,
    OrigoidApi.IssteRecordDataFovissteHistoryItem
> = core.serialization.object({
    agency: core.serialization.string().optional(),
    payrollOffice: core.serialization.string().optional(),
    periodType: core.serialization.string().optional(),
    startDate: core.serialization.string().optional(),
    endDate: core.serialization.string().optionalNullable(),
    baseSalary: core.serialization.string().optional(),
});

export declare namespace IssteRecordDataFovissteHistoryItem {
    export interface Raw {
        agency?: string | null;
        payrollOffice?: string | null;
        periodType?: string | null;
        startDate?: string | null;
        endDate?: (string | null) | null;
        baseSalary?: string | null;
    }
}
