/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const IssteRecordDataAffiliationAffiliationStatus: core.serialization.Schema<
    serializers.IssteRecordDataAffiliationAffiliationStatus.Raw,
    OrigoidApi.IssteRecordDataAffiliationAffiliationStatus
> = core.serialization.enum_(["ACTIVO", "INACTIVO", "FINADO", ""]);

export declare namespace IssteRecordDataAffiliationAffiliationStatus {
    export type Raw = "ACTIVO" | "INACTIVO" | "FINADO" | "";
}
