/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { IssteRecordDataClinicType } from "./IssteRecordDataClinicType";

export const IssteRecordDataClinic: core.serialization.ObjectSchema<
    serializers.IssteRecordDataClinic.Raw,
    OrigoidApi.IssteRecordDataClinic
> = core.serialization.object({
    code: core.serialization.string().optional(),
    type: IssteRecordDataClinicType.optional(),
    name: core.serialization.string().optional(),
    address: core.serialization.string().optional(),
    issteDelegation: core.serialization.string().optional(),
    phone: core.serialization.string().optional(),
});

export declare namespace IssteRecordDataClinic {
    export interface Raw {
        code?: string | null;
        type?: IssteRecordDataClinicType.Raw | null;
        name?: string | null;
        address?: string | null;
        issteDelegation?: string | null;
        phone?: string | null;
    }
}
