/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const IssteRecordDataPensionsItemCategory: core.serialization.Schema<
    serializers.IssteRecordDataPensionsItemCategory.Raw,
    OrigoidApi.IssteRecordDataPensionsItemCategory
> = core.serialization.enum_(["DIRECT", "SURVIVOR", "INSURANCE", "DISABILITY"]);

export declare namespace IssteRecordDataPensionsItemCategory {
    export type Raw = "DIRECT" | "SURVIVOR" | "INSURANCE" | "DISABILITY";
}
