/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { IssteRecordDataPensionsItemCategory } from "./IssteRecordDataPensionsItemCategory";

export const IssteRecordDataPensionsItem: core.serialization.ObjectSchema<
    serializers.IssteRecordDataPensionsItem.Raw,
    OrigoidApi.IssteRecordDataPensionsItem
> = core.serialization.object({
    category: IssteRecordDataPensionsItemCategory.optionalNullable(),
    agency: core.serialization.string().optional(),
    payrollOffice: core.serialization.string().optional(),
    startDate: core.serialization.string().optional(),
    pensionNumber: core.serialization.string().optional(),
    pensionType: core.serialization.string().optional(),
    pensionAmount: core.serialization.number().optional(),
});

export declare namespace IssteRecordDataPensionsItem {
    export interface Raw {
        category?: (IssteRecordDataPensionsItemCategory.Raw | null) | null;
        agency?: string | null;
        payrollOffice?: string | null;
        startDate?: string | null;
        pensionNumber?: string | null;
        pensionType?: string | null;
        pensionAmount?: number | null;
    }
}
