/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const LivenessDataSelfieAnalysisImageQuality: core.serialization.Schema<
    serializers.LivenessDataSelfieAnalysisImageQuality.Raw,
    OrigoidApi.LivenessDataSelfieAnalysisImageQuality
> = core.serialization.enum_(["excellent", "good", "poor"]);

export declare namespace LivenessDataSelfieAnalysisImageQuality {
    export type Raw = "excellent" | "good" | "poor";
}
