/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const LivenessDataSelfieAnalysisOrientation: core.serialization.Schema<
    serializers.LivenessDataSelfieAnalysisOrientation.Raw,
    OrigoidApi.LivenessDataSelfieAnalysisOrientation
> = core.serialization.enum_([
    "front",
    "looking_left",
    "looking_right",
    "looking_up",
    "looking_down",
    "tilted",
    "sideways",
]);

export declare namespace LivenessDataSelfieAnalysisOrientation {
    export type Raw =
        "front" | "looking_left" | "looking_right" | "looking_up" | "looking_down" | "tilted" | "sideways";
}
