/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const LivenessDataSelfieAnalysisDetectionConfidence: core.serialization.Schema<
    serializers.LivenessDataSelfieAnalysisDetectionConfidence.Raw,
    OrigoidApi.LivenessDataSelfieAnalysisDetectionConfidence
> = core.serialization.enum_(["high", "medium", "low"]);

export declare namespace LivenessDataSelfieAnalysisDetectionConfidence {
    export type Raw = "high" | "medium" | "low";
}
