/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { LivenessDataSelfieAnalysisImageQuality } from "./LivenessDataSelfieAnalysisImageQuality";
import { LivenessDataSelfieAnalysisDetectionConfidence } from "./LivenessDataSelfieAnalysisDetectionConfidence";
import { LivenessDataSelfieAnalysisOrientation } from "./LivenessDataSelfieAnalysisOrientation";
import { LivenessDataSelfieAnalysisIssuesItem } from "./LivenessDataSelfieAnalysisIssuesItem";

export const LivenessDataSelfieAnalysis: core.serialization.ObjectSchema<
    serializers.LivenessDataSelfieAnalysis.Raw,
    OrigoidApi.LivenessDataSelfieAnalysis
> = core.serialization.object({
    imageQuality: LivenessDataSelfieAnalysisImageQuality.optional(),
    detectionConfidence: LivenessDataSelfieAnalysisDetectionConfidence.optional(),
    orientation: LivenessDataSelfieAnalysisOrientation.optional(),
    eyesOpen: core.serialization.boolean().optionalNullable(),
    mouthOpen: core.serialization.boolean().optionalNullable(),
    wearingGlasses: core.serialization.boolean().optionalNullable(),
    wearingSunglasses: core.serialization.boolean().optionalNullable(),
    faceCovered: core.serialization.boolean().optionalNullable(),
    issues: core.serialization.list(LivenessDataSelfieAnalysisIssuesItem).optional(),
});

export declare namespace LivenessDataSelfieAnalysis {
    export interface Raw {
        imageQuality?: LivenessDataSelfieAnalysisImageQuality.Raw | null;
        detectionConfidence?: LivenessDataSelfieAnalysisDetectionConfidence.Raw | null;
        orientation?: LivenessDataSelfieAnalysisOrientation.Raw | null;
        eyesOpen?: (boolean | null) | null;
        mouthOpen?: (boolean | null) | null;
        wearingGlasses?: (boolean | null) | null;
        wearingSunglasses?: (boolean | null) | null;
        faceCovered?: (boolean | null) | null;
        issues?: LivenessDataSelfieAnalysisIssuesItem.Raw[] | null;
    }
}
