/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";
import { LivenessDataConfidence } from "./LivenessDataConfidence";
import { LivenessDataSelfieAnalysis } from "./LivenessDataSelfieAnalysis";

export const LivenessData: core.serialization.ObjectSchema<serializers.LivenessData.Raw, OrigoidApi.LivenessData> =
    core.serialization.object({
        isLive: core.serialization.boolean().optional(),
        livenessScore: core.serialization.number().optionalNullable(),
        confidence: LivenessDataConfidence.optionalNullable(),
        selfieAnalysis: LivenessDataSelfieAnalysis.optionalNullable(),
    });

export declare namespace LivenessData {
    export interface Raw {
        isLive?: boolean | null;
        livenessScore?: (number | null) | null;
        confidence?: (LivenessDataConfidence.Raw | null) | null;
        selfieAnalysis?: (LivenessDataSelfieAnalysis.Raw | null) | null;
    }
}
