/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const LivenessDataSelfieAnalysisIssuesItem: core.serialization.Schema<
    serializers.LivenessDataSelfieAnalysisIssuesItem.Raw,
    OrigoidApi.LivenessDataSelfieAnalysisIssuesItem
> = core.serialization.enum_([
    "wearing_glasses",
    "wearing_sunglasses",
    "face_covered",
    "eyes_closed",
    "poor_image_quality",
    "not_facing_camera",
    "low_detection_confidence",
]);

export declare namespace LivenessDataSelfieAnalysisIssuesItem {
    export type Raw =
        | "wearing_glasses"
        | "wearing_sunglasses"
        | "face_covered"
        | "eyes_closed"
        | "poor_image_quality"
        | "not_facing_camera"
        | "low_detection_confidence";
}
