/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as OrigoidApi from "../../api/index";
import * as core from "../../core";

export const LivenessDataConfidence: core.serialization.Schema<
    serializers.LivenessDataConfidence.Raw,
    OrigoidApi.LivenessDataConfidence
> = core.serialization.enum_(["HIGH", "MEDIUM", "LOW"]);

export declare namespace LivenessDataConfidence {
    export type Raw = "HIGH" | "MEDIUM" | "LOW";
}
