/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const CheckLivenessRequest: core.serialization.Schema<
    serializers.CheckLivenessRequest.Raw,
    OrigoidApi.CheckLivenessRequest
> = core.serialization.object({
    selfie: core.serialization.string(),
    allowMultipleFaces: core.serialization.boolean().optional(),
});

export declare namespace CheckLivenessRequest {
    export interface Raw {
        selfie: string;
        allowMultipleFaces?: boolean | null;
    }
}
