/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { MatchFacesRequestDocumentType } from "../../types/MatchFacesRequestDocumentType";

export const MatchFacesRequest: core.serialization.Schema<
    serializers.MatchFacesRequest.Raw,
    OrigoidApi.MatchFacesRequest
> = core.serialization.object({
    face: core.serialization.string(),
    front: core.serialization.string(),
    threshold: core.serialization.number().optional(),
    documentType: MatchFacesRequestDocumentType.optional(),
});

export declare namespace MatchFacesRequest {
    export interface Raw {
        face: string;
        front: string;
        threshold?: number | null;
        documentType?: MatchFacesRequestDocumentType.Raw | null;
    }
}
