/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         email: "user@example.com"
 *     }
 *
 * @example
 *     {
 *         email: "user@example.com"
 *     }
 *
 * @example
 *     {
 *         email: "user@example.com"
 *     }
 *
 * @example
 *     {
 *         email: "user@example.com"
 *     }
 *
 * @example
 *     {
 *         email: "user@example.com"
 *     }
 *
 * @example
 *     {
 *         email: "user@example.com"
 *     }
 *
 * @example
 *     {
 *         email: "user@example.com"
 *     }
 */
export interface ValidateEmailRequest {
    /** The email address to be validated. */
    email: string;
}
