/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const ExtractVoterIdDataRequest: core.serialization.Schema<
    serializers.ExtractVoterIdDataRequest.Raw,
    OrigoidApi.ExtractVoterIdDataRequest
> = core.serialization.object({
    front: core.serialization.string(),
    back: core.serialization.string().optional(),
});

export declare namespace ExtractVoterIdDataRequest {
    export interface Raw {
        front: string;
        back?: string | null;
    }
}
