/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const ExtractQrDataRequest: core.serialization.Schema<
    serializers.ExtractQrDataRequest.Raw,
    OrigoidApi.ExtractQrDataRequest
> = core.serialization.object({
    back: core.serialization.string(),
});

export declare namespace ExtractQrDataRequest {
    export interface Raw {
        back: string;
    }
}
