/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         selfie: "selfie"
 *     }
 *
 * @example
 *     {
 *         selfie: "selfie"
 *     }
 *
 * @example
 *     {
 *         selfie: "selfie"
 *     }
 *
 * @example
 *     {
 *         selfie: "selfie"
 *     }
 *
 * @example
 *     {
 *         selfie: "selfie"
 *     }
 *
 * @example
 *     {
 *         selfie: "selfie"
 *     }
 *
 * @example
 *     {
 *         selfie: "selfie"
 *     }
 *
 * @example
 *     {
 *         selfie: "selfie"
 *     }
 *
 * @example
 *     {
 *         selfie: "selfie"
 *     }
 *
 * @example
 *     {
 *         selfie: "selfie"
 *     }
 */
export interface CheckLivenessRequest {
    /** Selfie image of the subject in Base64 (PNG/JPG). */
    selfie: string;
}
