/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as OrigoidApi from "../../../../index";

/**
 * @example
 *     {
 *         face: "face",
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         face: "face",
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         face: "face",
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         face: "face",
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         face: "face",
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         face: "face",
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         face: "face",
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         face: "face",
 *         front: "front"
 *     }
 *
 * @example
 *     {
 *         face: "face",
 *         front: "front"
 *     }
 */
export interface MatchFacesRequest {
    /** Face image (selfie) in Base64 (PNG/JPG) */
    face: string;
    /** Front ID image in Base64 (PNG/JPG). Can be any official document globally. */
    front: string;
    /** Acceptance threshold (1-100). Default: 80. */
    threshold?: number;
    /** Optional. Use a specific type (e.g., 'INE', 'MEX_PASSPORT') for strict validation against that exact document type. Use 'ANY' to require the image be SOME recognized ID (auto-detected) — returns NO_DOCUMENT_DETECTED if not. Omit entirely for permissive mode (face match only, no document validation — intended for non-KYC use cases). */
    documentType?: OrigoidApi.MatchFacesRequestDocumentType;
}
