/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OrigoidApi from "../../../../api/index";
import * as core from "../../../../core";

export const ValidateCepRequest: core.serialization.Schema<
    serializers.ValidateCepRequest.Raw,
    OrigoidApi.ValidateCepRequest
> = core.serialization.undiscriminatedUnion([core.serialization.unknown()]);

export declare namespace ValidateCepRequest {
    export type Raw = unknown;
}
