/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Authentication } from "./api/resources/authentication/client/Client";
import { Renapo } from "./api/resources/renapo/client/Client";
import { SocialSecurity } from "./api/resources/socialSecurity/client/Client";
import { Ine } from "./api/resources/ine/client/Client";
import { Biometrics } from "./api/resources/biometrics/client/Client";
import { Compliance } from "./api/resources/compliance/client/Client";
import { Email } from "./api/resources/email/client/Client";
import { ProofOfAddress } from "./api/resources/proofOfAddress/client/Client";
import { Fiscal } from "./api/resources/fiscal/client/Client";
import { Banking } from "./api/resources/banking/client/Client";

export declare namespace OrigoidApiClient {
    export interface Options {
        environment?: core.Supplier<environments.OrigoidApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class OrigoidApiClient {
    protected _authentication: Authentication | undefined;
    protected _renapo: Renapo | undefined;
    protected _socialSecurity: SocialSecurity | undefined;
    protected _ine: Ine | undefined;
    protected _biometrics: Biometrics | undefined;
    protected _compliance: Compliance | undefined;
    protected _email: Email | undefined;
    protected _proofOfAddress: ProofOfAddress | undefined;
    protected _fiscal: Fiscal | undefined;
    protected _banking: Banking | undefined;

    constructor(protected readonly _options: OrigoidApiClient.Options) {}

    public get authentication(): Authentication {
        return (this._authentication ??= new Authentication(this._options));
    }

    public get renapo(): Renapo {
        return (this._renapo ??= new Renapo(this._options));
    }

    public get socialSecurity(): SocialSecurity {
        return (this._socialSecurity ??= new SocialSecurity(this._options));
    }

    public get ine(): Ine {
        return (this._ine ??= new Ine(this._options));
    }

    public get biometrics(): Biometrics {
        return (this._biometrics ??= new Biometrics(this._options));
    }

    public get compliance(): Compliance {
        return (this._compliance ??= new Compliance(this._options));
    }

    public get email(): Email {
        return (this._email ??= new Email(this._options));
    }

    public get proofOfAddress(): ProofOfAddress {
        return (this._proofOfAddress ??= new ProofOfAddress(this._options));
    }

    public get fiscal(): Fiscal {
        return (this._fiscal ??= new Fiscal(this._options));
    }

    public get banking(): Banking {
        return (this._banking ??= new Banking(this._options));
    }
}
