/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const OrigoidApiEnvironment = {
    Default: "https://api.origoid.com",
} as const;

export type OrigoidApiEnvironment = typeof OrigoidApiEnvironment.Default;
