/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LookupCurpRequestGender = "H" | "M" | "X";
export const LookupCurpRequestGender = {
    H: "H",
    M: "M",
    X: "X",
} as const;
