/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as OrigoidApi from "../../../../api/index";
import * as core from "../../../../core";

export const ValidateVoterListRequest: core.serialization.Schema<
    serializers.ValidateVoterListRequest.Raw,
    OrigoidApi.ValidateVoterListRequest
> = core.serialization.undiscriminatedUnion([core.serialization.unknown()]);

export declare namespace ValidateVoterListRequest {
    export type Raw = unknown;
}
