/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         rfc: "GARM900101HDF"
 *     }
 *
 * @example
 *     {
 *         rfc: "GARM900101HDF"
 *     }
 *
 * @example
 *     {
 *         rfc: "GARM900101HDF"
 *     }
 *
 * @example
 *     {
 *         rfc: "GARM900101HDF"
 *     }
 *
 * @example
 *     {
 *         rfc: "GARM900101HDF"
 *     }
 *
 * @example
 *     {
 *         rfc: "GARM900101HDF"
 *     }
 */
export interface ValidateRfcRequest {
    /** Taxpayer's RFC (12 or 13 characters). */
    rfc: string;
}
