/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const IssueTokenRequest: core.serialization.Schema<
    serializers.IssueTokenRequest.Raw,
    OrigoidApi.IssueTokenRequest
> = core.serialization.object({
    expireAfter: core.serialization.number().optional(),
});

export declare namespace IssueTokenRequest {
    export interface Raw {
        expireAfter?: number | null;
    }
}
