/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const GetImssEmploymentStatusRequest: core.serialization.Schema<
    serializers.GetImssEmploymentStatusRequest.Raw,
    OrigoidApi.GetImssEmploymentStatusRequest
> = core.serialization.object({
    curp: core.serialization.string(),
    nss: core.serialization.string(),
});

export declare namespace GetImssEmploymentStatusRequest {
    export interface Raw {
        curp: string;
        nss: string;
    }
}
