/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const GetIssteRecordRequest: core.serialization.Schema<
    serializers.GetIssteRecordRequest.Raw,
    OrigoidApi.GetIssteRecordRequest
> = core.serialization.object({
    curp: core.serialization.string(),
});

export declare namespace GetIssteRecordRequest {
    export interface Raw {
        curp: string;
    }
}
