/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as OrigoidApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const LookupImssNssRequest: core.serialization.Schema<
    serializers.LookupImssNssRequest.Raw,
    OrigoidApi.LookupImssNssRequest
> = core.serialization.object({
    curp: core.serialization.string(),
});

export declare namespace LookupImssNssRequest {
    export interface Raw {
        curp: string;
    }
}
